### ISSUE TITLE
How Can I kill/stop the Schedule

### ISSUE THREAD

**Issue by AvinashBakshi** [dbader/schedule#104]

**Comment by WoLfulus** [comment]
return `schedule.CancelJob` on the job function

**Comment by dbader** [comment]
Thanks @WoLfulus! That's exactly what I was going to recommend :)

@AvinashBakshi: Also check out this question in the FAQ: https://github.com/dbader/schedule/blob/master/FAQ.rst#how-can-i-run-a-job-only-once

Thanks for your question. Closing this so we can keep the tracker clean of loose ends. Feel free to follow up (or make a separate issue) with more questions/discussion 😃
