### ISSUE TITLE
Support for Python 3.5

### ISSUE THREAD

**Issue by fkromer** [dbader/schedule#109]
Hi @dbader , are you planning to support Python 3.5?

**Comment by dbader** [comment]
Hi @fkromer – yup, it works fine on 3.5 and we're now building against 3.5 on CI with #79. I just forgot to bump the version in `setup.py` :) If you want you can create a tiny PR for that, otherwise I'll do it later today. Thanks!

**Comment by dbader** [comment]
Closed in #110
