### ISSUE TITLE
Schedule events which are aligned to the calendar

### ISSUE THREAD

**Issue by khpeek** [dbader/schedule#114]
The [Periodic Interval of Time (PIVL)](https://www.oasis-open.org/committees/ubl/lcsc/doc/qateam/Comment%20work%20from%20HL7/datatypes.html#dt-PIVL) data type has an 'alignment' property which specifies if and how the repetitions are aligned to the cycles of the underlying calendar (e.g., to distinguish every 30 days from "the 5th of every month"). A non-aligned periodic interval recurs independently from the calendar, whereas an aligned one is synchronized with the calendar.

As I understand it, events scheduled by `schedule` are currently of the non-aligned type (similar to cron). Enhancing it to include calendar-aligned periodic intervals might be useful.

**Comment by dgrant** [comment]
Propose for closing? @dbader

**Comment by SijmenHuizenga** [comment]
Hi @khpeek, thanks for teaching me something :) Calendar alignment seems like quite an advanced topic that only a few users would benefit from. Schedule is a simple library and adding something like this doesn't fit well in that philosophy.
