### ISSUE TITLE
Add automated pypi deployment on new release using travis CI?

### ISSUE THREAD

**Issue by seemethere** [dbader/schedule#118]
I recently started using automated pypi deployment on a couple of my projects and I feel like schedule could really benefit from it.

Instructions on how to do it are here:
https://docs.travis-ci.com/user/deployment/pypi/

It's as simple as running a couple of commands.

**Comment by dbader** [comment]
That's great, thank you @seemethere. I'm going to set this up for the next release.

**Comment by dbader** [comment]
Actually thinking about this some more I don't feel comfortable handing my PyPI password over to TravisCI. Sure it's encrypted at rest, but they might leak their decryption key accidentally at some point. Closing for now.
