### ISSUE TITLE
support CRON expression

### ISSUE THREAD

**Issue by Sispheor** [dbader/schedule#119]
I would be interesting to create a job from a [cron expression](https://en.wikipedia.org/wiki/Cron#CRON_expression).

For exemple, I want to schedule a job every day a 7 I would use something like
`schedule.cronline("0 7 * * *").do(job)`

Here the same example for weekday at 8:30
`schedule.cronline("30 8 * * 1-5").do(job)`

It is something implemented in [python-crontab ](https://pypi.python.org/pypi/python-crontab)lib. See `job.setall(string)`

**Comment by dbader** [comment]
Hi @Sispheor :wave:

Thanks for raising the question but supporting Cron's syntax is out of scope for Schedule. The goal for Schedule is to provide an alternative / "more readable" (I know this is subjective) syntax for scheduling recurring jobs. Thanks for pointing out Python-crontab. I'm sure it'll be helpful for some folks!

Closing this for now to keep the tracker clean. Please feel free to re-open or create a follow up issue if you have any other questions. Thanks!
