### ISSUE TITLE
Does schedule support persistence of scheduled jobs?

### ISSUE THREAD

**Issue by scott-mead** [dbader/schedule#121]
I.e. to survive reboot, etc... ?

**Comment by dbader** [comment]
Hi @scott-mead 👋 

Schedule doesn't support job persistence at the moment and the verdict so far has been that job persistence is out of scope for the project. If you're interested you can check out the previous on this ticket and the ones linked to it: https://github.com/dbader/schedule/issues/17

Closing this for now to keep the tracker clean. Please feel free to re-open or create a follow up issue if you have any other questions. Thanks!
