### ISSUE TITLE
Does this package work with python 2.7.12?

### ISSUE THREAD

**Issue by gregv21v** [dbader/schedule#122]
I'm running this package on a linux server with python 2.7.12. I'm also running it on a windows machine with python 2.7.10 and it does work. Both places have the exact same code.

**Comment by dbader** [comment]
Hi @gregv21v :wave: Are you seeing any specific issues on Python 2.7.12 on Linux? I don't see why it wouldn't work :)

**Comment by gregv21v** [comment]
Hi I figured out the issue. There was a problem with my system being set to a different time then I was looking at.
