### ISSUE TITLE
How can I test?

### ISSUE THREAD

**Issue by Juanvulcano** [dbader/schedule#123]
Hi guys, I use Ubuntu on a VM. Let's suppose I want to test if a command that is meant to run every X days works. How can I speed up my local timer or do whatever is recommended? 
Do you have any unit test for this?

**Comment by FergusClare** [comment]
I tested by modifying my code from running daily to running every second.  For example:

Daily schedule:
`schedule.every().day.at(time).do(task)`
Second schedule:
`schedule.every(1).seconds.do(task)`

Then be sure to include the conditional check to run the scheduled task:
`while True:
     schedule.run_pending()
     time.sleep(x)`

This worked for me.

**Comment by bbengfort** [comment]
We use [freezegun](https://github.com/spulec/freezegun) as follows:

```python
import schedule

from freezegun import freeze_time
from unittest.mock import MagicMock
from datetime import datetime, timedelta

def test_schedule_weekly():
    mockTask = MagicMock()
    m = lambda: mockTask(datetime.now())

    start = datetime(2017, 1, 1, 0, 0)
    until = datetime(2018, 1, 1, 0, 0)
    with freeze_time(start) as fzdt:

        scheduler = schedule.Scheduler()
        scheduler.every().sunday.at("6:00").do(m)

        while datetime.now() < until:
            fzdt.tick(delta=timedelta(minutes=15))
            scheduler.run_pending()

    assert mockTask.call_count == 52
```

**Comment by SijmenHuizenga** [comment]
Take a look at the [code that tests the library] to learn how to mock datetime and assert next_runs.
