### ISSUE TITLE
Schedule jobs every X minutes but stagger them

### ISSUE THREAD

**Issue by slzatz** [dbader/schedule#126]
There is an issue related to scheduling ever hour at a certain time but I have a different problem.  I would like to stagger 3 tasks that will run every 30 min so (although the 30 min could vary):

task 1: runs at 0:00, 0:30 and repeats
task 2: runs at 0:10, 0:40 and repeats
task 3 runs at 0:20, 0:50 and repeats

Is the best way to do this to just separately schedule each task twice and do that every hour so task 1 is scheduled every hour at 0:00 and separately scheduled every hour at 0:30 and so on?

**Comment by SijmenHuizenga** [comment]
Yes, the best way is to separately schedule each task.
