### ISSUE TITLE
how to exit subprocess when i use fork()  in my funcion?

### ISSUE THREAD

**Issue by Y-Rookie** [dbader/schedule#128]
for example,
def my_job():
     ...
     fork()
     ...

def run_threaded(job_func):
    job_thread = threading.Thread(target=job_func)
    job_thread.start()

schedule.every(10).seconds.do(run_threaded, my_job)

while 1:
    schedule.run_pending()
    time.sleep(1)

i find that  could not exit the subprocess...

**Comment by dbader** [comment]
Closing this for now, this seems to be a threading issue that has nothing to do with Schedule specifically.
