### ISSUE TITLE
Support for time ranges

### ISSUE THREAD

**Issue by maxnoe** [dbader/schedule#132]
I'm looking for the functionality to do something only between certain times.
So, something like

```python
schedule.every(15).minutes.between('08:00', '16:00').do(cook_coffee)
```

**Comment by heisen273** [comment]
see #57

**Comment by heisen273** [comment]
also, see #16 , @imiric 's branch has between() function support.

**Comment by SijmenHuizenga** [comment]
Hi! I think executing a job between two times is quite specific and not really suited to be included in the library itself. You are probably better of running the task every 15 minutes and checking manually if the current time in the desired timeframe.
