### ISSUE TITLE
complex schedule

### ISSUE THREAD

**Issue by RaHaVe** [dbader/schedule#133]
Hi @dbader !
Thanks for your useful library!
I have issue - i need to run my task for example for n days starts at 1:00 and ends at 1:30 every 10 minutes (3 times per day) and need repeat this pattern until n days finish. Could you please help me?
many thanks!

**Comment by heisen273** [comment]
see #57

**Comment by fauzanM** [comment]
Problem Statement:
Run task in between 1:00 to 1:30 PM for specific no of days.

Solution:
Let's break down the problem:
1. Run task between 1:00 to 1:30
2. Run for specific no of days.

Run task between 1:00 to 1:30 - 
Look at the between functionality of the package something like:
https://github.com/dbader/schedule/issues/132

Run for specific no of days:
Work around would be a wrapper.

```
def run_at_specific_days():
today = datetime.datetime.now()
if self.start_day < today:
self.run_scheduler()
```

```
def run_scheduler():
# schedule between logic
while True:
schedule.run_pending()
time.sleep(1)

```

**Comment by mortezaipo** [comment]
Hi @RaHaVe , 
You can handle `end date` by `datetime` module:

```python
import datetime
import sys

# End date
end_day = 10
end_month = 3

def job():
    #  check the current date with the end date
    cur = datetime.datetime.now()
    if cur.day = end_day and cur.month == end_month:
        sys.exit()

    # otherwise, run your job
    print("hello world!")
```
