### ISSUE TITLE
Basic example not working

### ISSUE THREAD

**Issue by johnchristopher** [dbader/schedule#141]
```python
import time
import schedule


def job():
    print("I'm working...")


schedule.every(10).minutes.do(job)

while True:
    schedule.run_pending()
    time.sleep(1)
```
Nothing is displayed. I am running this on python 2.7.13 and windows 7 64 bits.

**Comment by heisen273** [comment]
Hi, John. I've tested your code and it works perfectly. 
Perhaps you should try to use 1 seconds interval, so you don't have to wait 10 minutes for first print.
