### ISSUE TITLE
Long process blocking other scheduled tasks

### ISSUE THREAD

**Issue by BugBounty13** [dbader/schedule#146]
Hi,
 
  I have this code running:

  ```
schedule.every(1).minute.do(regular_task)
  schedule.every(1).hour.do(some_long_running_task)

  while True:
      schedule.run_pending()
```

Unfortunately, the "some_long_running_task" takes more than 1 minute to complete so the "regular_task" method is not called on time. Is there a way to ensure that "regular_task" is always called, possibly in a background thread so that even if "some_long_running_task" hasn't completed, the regular task is called?

Thanks

**Comment by dmos62** [comment]
Sounds like you answered your own question. Delegate execution to other threads.

https://schedule.readthedocs.io/en/stable/faq.html#how-to-execute-jobs-in-parallel
