### ISSUE TITLE
Issue while creating new schedule.Scheduler() object. Jobs not running. 

### ISSUE THREAD

**Issue by Fauzan-M** [dbader/schedule#151]
Sample code:
`works = schedule.Scheduler()`
`works.every().at("00:00").do(self.run)`

This does nothing. Am I missing something. Ideally, it should allocate a new_array called self.job and work accordingly right ?

**Comment by WoLfulus** [comment]
```
while True:
    schedule.run_pending()
    time.sleep(1)
```

**Comment by Fauzan-M** [comment]
@WoLfulus. Figured out the issue, its not with run_pending(). But, thanks anyway.

**Comment by WoLfulus** [comment]
What was it? Just in case someone else needs. :)

**Comment by Fauzan-M** [comment]
I used the wrong schedule object while specifying schedule.run_pending(). 

`worker = schedule.Scheduler()
worker.every().minutes.do(self.run_task)

while True:
schedule.run_pending()
`

The mistake was at **schedule.run_pending()**. It should have been worker.run_pending(). As schedule object has no jobs assigned. That's why it did not run.
