### ISSUE TITLE
High CPU usage (100%) on simple code

### ISSUE THREAD

**Issue by mortezaipo** [dbader/schedule#156]
When I run this sample code, it take 100% of CPU:

```python
import schedule

def job():
    print("hello world!")

schedule.every().minutes.do(job)

while True:
    schedule.run_pending()
```

`htop` result:

`
5835 morteza    20   0 31624  9788  5116 R 99.5  0.1  0:24.97 ./venn/bin/python sample.py
`

Current usage in this report: `99.5%`

**Comment by dbader** [comment]
Hi @mortezaipo, you need a `time.sleep()` call in there to give up some CPU on every iteration (cf. FAQ examples), otherwise the `while` pegs the CPU.
