### ISSUE TITLE
it works fine with scrapy module

### ISSUE THREAD

**Issue by lawlietfans** [dbader/schedule#157]
this module works fine with scrapy module, but do not using buitin `scrapy.cmdline`

```py
def crawl_work():
    cmdline.execute('scrapy crawl my_spider'.split())
if __name__=='__main__':
    schedule.every(1).minutes.do(crawl_work)
    while True:
            schedule.run_pending()
            time.sleep(1)
```
run only once, the program will exited.

change the scrapy.cmdline to subprocess
```py
def crawl_work():
    subprocess.Popen('scrapy crawl my_spider')
```
it works very well

**Comment by dbader** [comment]
Hey there, looks like `cmdline.execute` calls `sys.exit()` to quit the process: https://stackoverflow.com/questions/24875280/scrapy-cmdline-execute-stops-script
