### ISSUE TITLE
Scheduled web scraping and writing to csv

### ISSUE THREAD

**Issue by sakiskun** [dbader/schedule#158]
Guys i have a web scraper that will pull the data every 60secs, and that is working great. 
However, I am trying to save the data to a csv file and cant seem to do so.  Would appreciate and guidance...thanks:

f = open(filename, "a")

start_day = datetime.datetime.today().weekday()
end_day = datetime.datetime.today().weekday()
timer = datetime.datetime.today()

def job():
    start_day = 0
    end_day = 6
    if  today >= start_day and today <= end_day:
            
        dt = datetime.datetime.now().strftime("%A, %d. %B %Y %I:%M%p")   
        print(dt)
        print(long_sentimentAUD)
        print(long_sentimentEUR)
        print(long_sentimentJPY)
        print(long_sentimentGBP)
        print(long_sentimentGOLD)
        print(long_sentimentAUSSIE200)
        print(long_sentimentGERMANY30)
        print(long_sentimentWALLSTREET)
        print(long_sentimentWTI)
             
schedule.every(60).minutes.do(job)

while True:
        today = datetime.datetime.today().weekday()    
        schedule.run_pending()
        time.sleep(1)

f.write(dt + "," + long_sentimentAUD + "," + long_sentimentEUR + "," + long_sentimentJPY + "," +  long_sentimentGBP + "," + long_sentimentGOLD + "," + long_sentimentAUSSIE200 + 
        "," + long_sentimentGERMANY30 + "," + long_sentimentWALLSTREET + "," + long_sentimentWTI + "\n")
f.close()

**Comment by sdhutchins** [comment]
@sakiskun could you edit this so it is more readable?
