### ISSUE TITLE
Python 3 Does not Work

### ISSUE THREAD

**Issue by MasterOfTheTiger** [dbader/schedule#165]
It won't import to my python script.

**Comment by fauzanbaigm** [comment]
Is it possible for you to elaborate or post your script ?

**Comment by MasterOfTheTiger** [comment]
I used the example script. It imports successfully when I run it with
Python2, but it fails to import with Python3.

**Comment by fauzanbaigm** [comment]
Package installation was done via (for python3) -
`pip3 install schedule `
Also, check which version of python interpreter your IDE or editor is using as default. Mismatch of versions could lead to such irritating issues.

**Comment by MasterOfTheTiger** [comment]
Oh. :P. I am so dumb. I am new with Python. Sorry.

**Comment by fauzanbaigm** [comment]
No problem. Kindly close the issue.
