### ISSUE TITLE
How to read schedule from config file?

### ISSUE THREAD

**Issue by goldenbull** [dbader/schedule#167]
I need to read a list of jobs from configuration file in json format, which looks like:
```
{
  "jobs" : [
    { "id" : "job1", cron : "daily 11:30", "arg" : "this is an argument for job1" },
    { "id" : "job2", cron : "every 10 minutes", "arg" : 12.34 },
    ...
  ]
}
```
The `cron` field is just illustrative. Actually I would like to use crontab syntax which looks like:
```
schedule.add("* * * 30 *", worker_func)
```
but seems not supported yet. Any similar approach?

**Comment by fauzanbaigm** [comment]
If you could post the entire script. I might be able to help you. This raises too many assumptions for me. Sorry, kindly update the entire code or point me to your github repo.
