### ISSUE TITLE
Get next run by tag

### ISSUE THREAD

**Issue by wirelessbitstrips** [dbader/schedule#175]
It would nice to have an parameter for next_run which takes a tag...
e.g. schedule.next_run(tag) 
which returns the next run information for the given tag parameter.

schedule.every(5).minutes.do(soundMaker).tag('soundMaker')

To get the next time soundMaker would run you could do this...
nextTime = schedule.next_run('soundMaker') 

This could also be used to see if the item is scheduled already or it was canceled.
if schedule.next_run('soundMaker') != None:
    print('it is scheduled') # return True
else:
    print it is not scheduled # return False

**Comment by SijmenHuizenga** [comment]
Hi @wirelessbitstrips, thanks for the suggestion. I think it makes sense to support filtering jobs using tags when calling `next_run`. 

Anyone willing to create a pr for this?

**Comment by StevenChoo** [comment]
@SijmenHuizenga wouldn`t suffice to use the `get_jobs` function and then map the next_run time yourself. If we implement it a described above, you can have list of next_run dates and unless you map it to the job itself you don`t know which next_run time belongs to which job.
