### ISSUE TITLE
import schedule does not work. 

### ISSUE THREAD

**Issue by nikki21208** [dbader/schedule#183]
python no longer recognizes 'schedule' as a package

**Comment by lutzhorn** [comment]
What is your Python version? How did you install it? How did you install `schedule`?

**Comment by nikki21208** [comment]
Hi, I installed 2.7 from the python website. When I tried to import
schedule, python didn't recognize it.

**Comment by dbader** [comment]
Any chance you have another module called `schedule.py` in your project? 

-> https://schedule.readthedocs.io/en/stable/faq.html#i-m-getting-an-attributeerror-module-object-has-no-attribute-every-when-i-try-to-use-schedule-how-can-i-fix-this

**Comment by WikiWookie** [comment]
Having this problem.

C:\Users\wookie\spacework\lonestarsignuppy (master)
λ pip install schedule
Collecting schedule
  Using cached schedule-0.5.0-py2.py3-none-any.whl
Installing collected packages: schedule
Successfully installed schedule-0.5.0

C:\Users\wookie\spacework\lonestarsignuppy (master)
λ py cron.py
Traceback (most recent call last):
  File "cron.py", line 1, in <module>
    import schedule
ModuleNotFoundError: No module named 'schedule'

----------------------------------------------------------------------
import schedule
import time

def job():
  print("I'm working...")

schedule.every(1).minutes.do(job)
# schedule.every().hour.do(job)
# schedule.every().day.at("10:30").do(job)
# schedule.every().monday.do(job)
# schedule.every().wednesday.at("13:15").do(job)

while True:
  schedule.run_pending()
  time.sleep(1)

**Comment by yash1th** [comment]
@WikiWookie I recommend you use virtual environments when installing any library. The more you work on projects, you realize that do not want to install your libraries on a global level

**Comment by WikiWookie** [comment]
@yash1th I agree, I'm used to NodeJS where I can install everything locally and bring it into my projects
