### ISSUE TITLE
About timezone in the "schedule.every().day.at" function

### ISSUE THREAD

**Issue by dizhu1991** [dbader/schedule#187]
Hi @dbader 

I wrote a line of code:

schedule.every().day.at("23:55").do(job())

Is "23:55" here UTC? 

Thanks.

**Comment by kmonsoor** [comment]
@dizhu1991 i think, it should be the system-time on which `schedule` is running.

**Comment by filipre** [comment]
It would be useful to state this in the documentation.

**Comment by cdeil** [comment]
@dbader  Is the time given in [schedule.Job.at](https://schedule.readthedocs.io/en/stable/api.html#schedule.Job.at) in UTC?

Would be really good to mention somewhere in the docs what time this refers to:
```
schedule.every().day.at("10:30").do(job)
```

**Comment by xmatthias** [comment]
I don't think it's in UTC - based on the code, `datetime.datetime.now()` is used - which is in system local timezone, not in UTC.

https://github.com/dbader/schedule/blob/8a944c845fb837545f990639b227c2bbfd2f53ba/schedule/__init__.py#L637-L642

It'd however be nice to be able to manually set the timezone - as it'll depend on the usecase if we need to run a job at 00:00 in local time, or at 00:00 in UTC timezone.

**Comment by Frankstar** [comment]
wow - i search way to long for that information ....
I think its good that schedule is using `datetime.datetime.now()` / system local timezone - especially cause we dont have a timezone support.

**Comment by SijmenHuizenga** [comment]
Yes, without specifying a timezone all timestamps are local-time. Support for specifying a timezone in `.at()` has been added in 1.2.0 :tada:
