### ISSUE TITLE
In jupyter, jobs are not printing when they are meant to

### ISSUE THREAD

**Issue by madsthaks** [dbader/schedule#188]
```
import schedule
import datetime

def job(message='stuff'):
    print("I'm working on:", message)

schedule.every(10).seconds.do(job)

schedule.cancel_job(job)
```

When I run `schedule.every(10).seconds.do(job)`, it just outputs this:

> Every 10 seconds do job() (last run: [never], next run: 2017-12-18 14:29:54)

Then when I run `schedule.run_all()`, it just prints:

> I'm working on: stuff

once when it should be printing every 10 seconds. Maybe I'm interpreting the documentation incorrectly.

**Comment by yeaske** [comment]
Did you implement below in a thread? That is needed to run every second to run any job pending based on schedule.

```
while True:
    schedule.run_pending()
    time.sleep(1)
```
