### ISSUE TITLE
Job.__repr__ causes a RecursionError when the job is passed to the do function as an arg.

### ISSUE THREAD

**Issue by jchacks** [dbader/schedule#190]
I wish to pass the job instance to the do function of the same job i.e. `do(some_function, job)`.  However, due to the way repr is defined for job this causes a `RecursionError`.
This is the culprit:
```python
args = [repr(x) for x in self.job_func.args]
```

**Comment by dbader** [comment]
Hey thanks for the report. Would be nice to prevent this from causing an error—if you (or anyone else) is interested in putting together a PR for this I'm all ears :-)

**Comment by JChacks** [comment]
@dbader  In my mind `__repr__` should return the minimal representation of the job, something similar to executable code i.e. 
```python
Job(every=1,unit=second,do=job,args=[self, 1])
```
and then the `__str__` representation would be the old `__repr__`:
```python
"Every 1 second do job(self, 1) (last run: [never], next run: 2017-12-28 16:09:08)']"
```
How does that sound, it might break a few of your tests, I will try to fix those as well.

**Comment by dbader** [comment]
I like the idea of retaining the current output as a human-readable `__str__` and modifying the repr to return a parseable representation of the Job object. I saw you started working on a PR, thanks :-)
