### ISSUE TITLE
Dumb Q: What is time.sleep() doing?

### ISSUE THREAD

**Issue by evilplanet** [dbader/schedule#209]
Hi,

I'm writing a function that gets run every 28 minutes as below:

```
import schedule
import time

def foo():
    print('do something')

schedule.every(28).minutes.do(foo)

while True:
    schedule.run_pending()
    time.sleep(1)
```

But I don't understand `time.sleep(1)` here. Do I need this here? I just want to make sure foo() gets called every 28 minutes. 

Also, how do I initialise the schedule, do I have to call it from somewhere? (This snippet will be in a Django project.)

Thank you!

**Comment by AlejandroCruz-0** [comment]
The 
```
while True:
    schedule.run_pending()
    time.sleep(1)
```
Initializes runs any pending that were defined in:
`schedule.every(28).minutes.do(foo)`
time.sleep(1) Basically is there to make sure the script doesn't hog all the CPU usage, it's very technical stuff. Try running a while true loop in python without sleep and see how much CPU usage it uses :)

**Comment by evilplanet** [comment]
@AlejandroCruz-0  Thank you! Now it's much clearer.
