### ISSUE TITLE
Countdown for the next job() ⏲

### ISSUE THREAD

**Issue by S1M0N38** [dbader/schedule#216]
Most of the time when you schedule a job the intervals time between the job() is greater that few minutes. So, I thought would be nice to print on the console the time left to the next job (a sort of countdown). And I think it's also prettier to update the line printed rather than print the line many times.

**Comment by mdesson** [comment]
For fun, I made something a little while back that could work pretty well for this, visually:
https://github.com/mdesson/mtools/blob/master/UpdatingStringInOneLine.py

It would just be a question of having it correctly display the time.

**Comment by Doxxxxxx** [comment]
I've done this to display a countdown:

```
    while True:
        schedule.run_pending()

        delta_next = datetime.timedelta(seconds=int(schedule.idle_seconds()))
        sys.stdout.write("\rNext job in {0}".format(str(delta_next)))
        sys.stdout.flush()

        time.sleep(1)
```

**Comment by SijmenHuizenga** [comment]
Great example @Doxxxxxx! I assume with that, this issue has been resolved. If not, feel free to comment down below.
