### ISSUE TITLE
Where is Job.mondays(), Job.thursdays(), ...? 

### ISSUE THREAD

**Issue by dstrigl** [dbader/schedule#221]
In your Job class for the weekdays you have some asserts, like:

    `assert self.interval == 1, 'Use mondays instead of monday'`

But where can I find this methods with ending '**s**' , e.g. monday**s**(), thursday**s**(), ...?

**Comment by f3n1Xx** [comment]
why use mondays() when you have job running every monday. Isn't it the same thing? please let me know if i am missing something.

**Comment by dstrigl** [comment]
No sorry, you are right!
