### ISSUE TITLE
how to schedule on reboot

### ISSUE THREAD

**Issue by MMd95** [dbader/schedule#222]
is there any method like schedule.every_reboot() or something like this?

**Comment by mdesson** [comment]
Do you mean something that runs just before the computer reboots or just after? What kind of usecase are you thinking?

**Comment by f3n1Xx** [comment]
i guess he means "at login" but with reboot being some sort of flag

**Comment by MMd95** [comment]
i need to do a job after pc reboots

**Comment by f3n1Xx** [comment]
I think a script would do the job, you can just call scheduler from the script everytime your computer reboots

**Comment by SijmenHuizenga** [comment]
This library is meant to be used inside a python process. If you need to launch a python script on boot, try googling "Python Launch on Boot".
