### ISSUE TITLE
Run at certain time if it's weekday ?

### ISSUE THREAD

**Issue by aykuter** [dbader/schedule#227]
Hey. Firstly thank you soo much for this package guys it's really helpful. I read documents but i couldn't find anything related my question. Is there any way to make it work on a certain time and if it's weekday ? Thanks!

**Comment by Proteusiq** [comment]
On the main page you:

schedule.every().wednesday.at("13:15").do(job)

as example.

**Comment by SijmenHuizenga** [comment]
Hi! I hope above comments helped you out. Built-in support for weekdays is not in schedule. A feature request for this is here #129. Feel free to comment or open a new issue if you have any more questions.
