### ISSUE TITLE
How would you pass a function call?

### ISSUE THREAD

**Issue by Shubbler** [dbader/schedule#230]
So I want to schedule a job, the method being called takes a `date` parameter.

I need to pass in `date.today()` each time the job is executed.

How would I do this?

``` python
    def notify_employees_day(date):
        ...


    schedule.every(5).hours.do(notify_employees_day, date.today)
```

**Comment by inkychris** [comment]
The `do` method declaration for the `Job` class is
```python
def do(job_func, *args, **kwargs)
```
The docs say that `args` and `kwargs` are passed on to the `job_func` so an example would be:
```python
import schedule, time

def func_takes_arg(arg):
    print(arg)

schedule.every(2).seconds.do(func_takes_arg, "Hello")
schedule.every(2).seconds.do(func_takes_arg, arg="World")

while True:
    schedule.run_pending()
    time.sleep(1)
```
The above code should print "Hello" and "World" every 2 seconds.

**Comment by Shubbler** [comment]
Nice one, for some reason couldn't think of that.

Cheers!
