### ISSUE TITLE
schedule every X but run the first execution at startup

### ISSUE THREAD

**Issue by domeniconappo** [dbader/schedule#237]
Hi,
I can't find an option to run immediately the first execution of a scheduled job.

We have jobs to run every 6 hours, but first execution must occur at startup (and not after 6 hours of application bootstrap). 

How can I achieve that?

**Comment by wrgsRay** [comment]
Using the example in the readme:

> import schedule
> import time
> 
> def job():
>     print("I'm working...")
> 
> schedule.every(10).minutes.do(job)
> schedule.every().hour.do(job)
> schedule.every().day.at("10:30").do(job)
> schedule.every(5).to(10).minutes.do(job)
> schedule.every().monday.do(job)
> schedule.every().wednesday.at("13:15").do(job)
> 
> while True:
>     schedule.run_pending()
>     time.sleep(1)

You can just add `job()` before `schedule.every(10).minutes.do(job)` to execute job once.

**Comment by domeniconappo** [comment]
🥇 
Thanks :)

**Comment by SijmenHuizenga** [comment]
something like this will do the job: 
```diff
 import schedule
 import time
 def job():
     print("I'm working...")
+job()
 schedule.every(10).minutes.do(job)

 while True:
     schedule.run_pending()
     time.sleep(1)
```
