### ISSUE TITLE
Async process jobs

### ISSUE THREAD

**Issue by avelino** [dbader/schedule#24]
On run `schedule.run_pending()` and exist 50 jobs and each job leads 20m, generate dead lock!

**Comment by dbader** [comment]
Hi @avelino, I realize this response might come a little late but can you share some example code that causes the behaviour you described? Thanks.

**Comment by avelino** [comment]
@dbader https://github.com/avelino/mining/blob/master/mining/bin/scheduler.py#L86:L122

In this infinite loop when one or more process takes more than 20 minute generates a dead lock in the "schedule".
