### ISSUE TITLE
confused log

### ISSUE THREAD

**Issue by woshidama323** [dbader/schedule#242]
when i use this lib to do some timer task in python code, 
i got some logs below which confused me .

``
    schedule.every().day.at("01:45").do(dailylucky)

    while True:
        schedule.run_pending()
        time.sleep(5)
``
2018-08-31 **01:45**:01,203 - schedule - INFO - Running job Every 1 day at 01:45:00 do dailylucky() (last run: [never], **next run: 2018-08-31 01:45:00**)

does it mean the task job would not run on next day ?   i mean the time **2018-09-01 01:45:00**

**Comment by Yonodactyl** [comment]
Hello woshidama.
Can you please clarify if your problem still exist or if you found a solution?

**Comment by naranjja** [comment]
Hi, I'm seeing this exact issue as well.

```python
def f():
   pass

schedule.every().day.at("10:00").do(f)

while True:
   schedule.run_pending()
   time.sleep(1)
```

At 10am, it shows on output:
```
Running job Every 1 day at 10:00:00 do f() (last run: [never], next run: 2018-11-05 10:00:00)
```

This is today's date, shouldn't it say `2018-11-06`?

**Comment by SijmenHuizenga** [comment]
Logging has changed a bit since this was submitted. Currently:
```
import schedule
import logging
import time

logging.basicConfig()
schedule_logger = logging.getLogger('schedule')
schedule_logger.setLevel(level=logging.DEBUG)

def foo():
    print("Hello, Logs")

schedule.every().second.do(foo)

schedule.run_all()
time.sleep(3)
schedule.run_pending()

```
outputs:
```
DEBUG:schedule:Running *all* 1 jobs with 0s delay inbetween
DEBUG:schedule:Running job Job(interval=1, unit=seconds, do=foo, args=(), kwargs={})
Hello, Logs
DEBUG:schedule:Running job Job(interval=1, unit=seconds, do=foo, args=(), kwargs={})
Hello, Logs
```

The `last run` and `next run` are no longer shown. If you feel that is a problem you are welcome to create a new issue.
