### ISSUE TITLE
Sub-minute resoulution

### ISSUE THREAD

**Issue by guydvir2** [dbader/schedule#246]
Hi,
Is there a way to have a more precise schedule ?
for example: start at every day 10:00:00 and stop at 10:00:20 ?

**Comment by Yonodactyl** [comment]
Hello guydvir2, I hope you are doing well today.
From my understanding of the documentation the option for sub-second duration is not currently available (as well as duration in general) and must be worked around.
A possible solution that I thought up would be to create a function and close it with a call to both the previously called function and to cancel the job once completed.
This would look something like this:
```
def job():
    # Does your normal task
    schedule.every().day.at("10:00").do(job)
    return schedule.CancelJob

schedule.every().day.at("10:00").do(job)
```

**Comment by SijmenHuizenga** [comment]
To run a job at a specific second, use the `.at()` method. To start every day at 10:00:00 use:
```
schedule.every().day.at('10:00:12').do(job)
```

Sub-second resolution is not supported.

**Comment by guydvir2** [comment]
thank you
