### ISSUE TITLE
Is there a "weekday" setting?

### ISSUE THREAD

**Issue by vgoklani** [dbader/schedule#249]
Is there a "weekday" setting, for jobs that only run M-F? Otherwise i have to do this:

	schedule.every().monday.at("7:15").do(something())
	schedule.every().tuesday.at("7:15").do(something())
	schedule.every().wednesday.at("7:15").do(something())
	schedule.every().thursday.at("7:15").do(something())
	schedule.every().friday.at("7:15").do(something())

**Comment by Yonodactyl** [comment]
Your best option is to have a feature that checks a condition that executes only if the days of the week are **not** Saturday or Sunday.
You can use int values from 0 to 6 and only execute if value < 5.

**Comment by mzjuin** [comment]
https://stackoverflow.com/questions/29384696/how-to-find-current-day-is-weekday-or-weekends-in-python/29384769

This works too.

**Comment by SijmenHuizenga** [comment]
Hi! This feature request is being tracked in #129.

If you feel like this request is different you are welcome to commend and we can re-open :)
