### ISSUE TITLE
schedule.every().day.at() is off by 13 hours

### ISSUE THREAD

**Issue by jethornton** [dbader/schedule#250]
schedule.every().day.at('05:00').do(test5)
should run test5 at 5am yet it runs at 6pm

Is there a way to link schedule to local time?

**Comment by Yonodactyl** [comment]
Hey jethornton,

Can you try something for me? Will you replace the ' with " and see if that does anything for you? I ran the code on my end and used 24 hour time to make sure it was running accurately at 9:40 PM.

**Comment by jethornton** [comment]
For anyone facing a similar problem and wanting to update something each day as the date changes the following code works well.
`		today = datetime.date(datetime.now(pytz.timezone('US/Central')))
		if lastDate != today:
			lastDate = today
			update()
`

**Comment by Yonodactyl** [comment]
Can you format the code so that i can rule out that you indented all your lines accordingly? From the sample you posted I cant tell if everything is accurately running.

**Comment by jethornton** [comment]
Of course it runs, I don't know why the indentation gets hacked here. I have other code running on the RPi that compares dates so I set the local timezone information in my Python program. What I failed to do is set the timezone information in the RPi. The following code revealed the problem with the first print() function.
`#!/usr/bin/env python3

import schedule
import time
from datetime import datetime

print('Schedule Test {}'.format(datetime.now().strftime('%b,%d %Y %I:%M%p')))

def update():
	print(datetime.now().strftime('%b,%d %Y %I:%M%p'))

schedule.every().day.at("00:01").do(update)

while True:
	schedule.run_pending()
	time.sleep(1)`

Output before setting the RPi timezone information is:
`pi@raspberrypi:~ $ stest
Schedule Test Oct,16 2018 05:10AM
`
And the time was 5:10PM at the time of the above test.

Output after setting the RPi timezone information is:
`pi@raspberrypi:~ $ stest
Schedule Test Oct,15 2018 06:15PM
`
The correct local time was 06:15PM when I ran the second test. I assume it will now run the update() function at 00:01AM. I will close this issue tomorrow after verifying that I didn't understand where schedule got it's time from. It might be a good thing to add to the documentation.

JT

And amazing this time the indentation is preserved.

**Comment by jethornton** [comment]
Well the indentation was preserved until I pressed the comment button lol...

**Comment by jethornton** [comment]
Ok this morning I see the following output which shows that it indeed does work,  now to prove or disprove the ' vs the " theory.
`pi@raspberrypi:~ $ stest

Schedule Test Oct,15 2018 06:15PM

Oct,16 2018 12:01AM
`

**Comment by jethornton** [comment]
I have verified that it makes no difference if you use ' or " makes no difference as stated above the system time zone must be set correctly for this to work on a day basis.
