### ISSUE TITLE
Option to use the system monotonic clock if possible instead of system time

### ISSUE THREAD

**Issue by rossmacarthur** [dbader/schedule#258]
It would be nice if there was an option to use the system monotonic clock, instead of the system time, so that cases where the time changes on the system, the schedule is not affected.

**Comment by SijmenHuizenga** [comment]
Using the system monotonic clock is quite specialized. Schedule's goal is to be a _simple_ scheduler. Using alternative clocks is quite advanced and thus out of scope.
