### ISSUE TITLE
Suggestion: Passing arrays into .at() method

### ISSUE THREAD

**Issue by MikeDoes** [dbader/schedule#269]
A simple suggestion to add the following functionality to make repetitive scheduling cleaner.

I tried parsing several arguments or arrays into the .at() function but it was only limited to one. If it would be possible to test for the type of input and then adapt the method, that would create a more 'human' approach.

For example, we could schedule in future we can schedule like so:

runtimes=["06:01","12:01","18:01","00:01"]
schedule.every().day.at(runtimes).do(scheduledtasks)

Rather than:

runtimes=["06:01","12:01","18:01","00:01"]
for launchpoint in runtimes:
_______schedule.every().day.at(launchpoint).do(scheduledtasks)

**Comment by SijmenHuizenga** [comment]
Hi @MikeDoes, thanks for this suggestion! You are right, doing `every().day.at("06:01", "12:01", "18:01", "00:01")` does read nicely. However, I don't think a loop is too bad either:

```
for time in ["06:01", "12:01", "18:01", "00:01"]:
    schedule.every().day.at(time).do(job)
``` 

Apart from being a human library, simplicity is quite important as well. Adding support for multiple values in `.at()` increases complexity quite a bit and raises the question if multiple `.every()` should also be supported. I think the rule of thumb that every job has a single interval is quite nice and keeps the library clean. If someone needs to run a job at multiple intervals, or with multiple `.at()` (or a combination), they can best schedule multiple jobs.
