### ISSUE TITLE
is there a way to change the scheduled time while the scheduled job is running ?

### ISSUE THREAD

**Issue by LogX7** [dbader/schedule#282]

**Comment by pawisoon** [comment]
I'm also interested if that's possible to do.

**Comment by LogX7** [comment]
@pawisoon i'm doing this using a hack .. but i think it's a bad idea 
- put the task you want to do in function A, 
- create another function B that calls that functions after checking if a counter C has reached a certain value T 
- if the value T is reached, C is reseted to 0 and function A is executed, otherwise C is incremented by 1, then schedule function B to run every 1 second 
- T and C are globals,
- whenever you want to change the scheduled time you just change T
