### ISSUE TITLE
bug in "schedule.every(1).hour.at()" function

### ISSUE THREAD

**Issue by tangb4c** [dbader/schedule#286]
`schedule.every(1).hour.at('03:02').do(job)`
will be parsed as  HH:MM, not MM:SS
not work as expected.

**Comment by eladbi** [comment]
I created a pull request for this issue:
https://github.com/dbader/schedule/pull/290

**Comment by SijmenHuizenga** [comment]
Hi! This has been solved in #290 released in v1.0.0.
