### ISSUE TITLE
Collections deprecated in 3.8

### ISSUE THREAD

**Issue by sabato-chris** [dbader/schedule#296]
Using the schedule module with my project, and testing with pytest, yields a warning about 3.8 dropping support for collections being called in the way its used.

Running python 3.7.3 with schedule 0.6.0 release.

[csabato@thor-teststand-1 unit_tests]$ python3 -V
Python 3.7.3
[csabato@thor-teststand-1 unit_tests]$ pip install -U schedule
Requirement already up-to-date: schedule in /usr/local/lib/python3.7/site-packages (0.6.0)
[csabato@thor-teststand-1 unit_tests]$

 /usr/local/lib/python3.7/site-packages/schedule/__init__.py:357: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    if not all(isinstance(tag, collections.Hashable) for tag in tags):

**Comment by jneilliii** [comment]
has this merged version not made it's way back to pypi.org yet? I noticed this same warning from an imported module.

**Comment by SijmenHuizenga** [comment]
This will be released in the next release, which is almost ready, :tada:, see #412
