### ISSUE TITLE
schedule monthly job!

### ISSUE THREAD

**Issue by leh08** [dbader/schedule#300]
Hi Dan

I would like to request a feature monthly scheduling job. I would be great, if you had that feature in your module.

Kind regards
Giang

**Comment by janfilips** [comment]
Please please I too need monthly scheduling job.

**Comment by gaguirregabiria** [comment]
I developed the monthly scheduling feature.
Right now the pull request is pending to be accepted and merged but you can download the code from my GitHub profile and test it.

Cheers,
Gari

**Comment by janfilips** [comment]
Rock star!  :)

**Comment by leh08** [comment]
Awesome, thanks so much!!

**Comment by SijmenHuizenga** [comment]
I see how this can be useful, but as described in #73 it is also prone to error. From a quick peek at #318, @gaguirregabiria's work on implementing monthly jobs looks good. Unfortunately support for long-running jobs is not a good fit for this library. Therefore i'm closing this issue.
