### ISSUE TITLE
 I found a bug in your code.and i fixed it

### ISSUE THREAD

**Issue by 4379711** [dbader/schedule#303]
description：
When I run a time-consuming program, if the program execution end time is on the second day, then the same day (second day) timed task will not start.
fixed：
in your code 466 lines  【ret = self.job_func()】，Put this line behind 468 lines，
The result should be:

`    def run(self):    

        logger.info('Running job %s', self)
        # ret = self.job_func()
        self.last_run = datetime.datetime.now()
        self._schedule_next_run()
        ret = self.job_func()
        return ret
`

**Comment by SijmenHuizenga** [comment]
Thanks a lot for reporting this! I am looking into this tonight. Closing this as a duplicate in favor #304.
