### ISSUE TITLE
Long-running daily job skipped every other day

### ISSUE THREAD

**Issue by neerajb1** [dbader/schedule#304]
Hi I am facing issue while using 
schedule.every().day.at("22:30")

I am calling script that is taking approx 5 hrs to complete. This schedule is skipping 1 day. It may be because it is completed next day at morning hence it is skipping that day. Please let me know how i can run script daily

**Comment by 4379711** [comment]
Hi,I submitted an issue for the solution to this bug, but the author did not reply to me.you can read #303
