### ISSUE TITLE
How to use job.Mondays()

### ISSUE THREAD

**Issue by nawfalassimi** [dbader/schedule#312]
Is it possible to schedule a job every two mondays ? 
The property mondays() doesnt exist ?

**Comment by maurokenny** [comment]
I would use every(60).days instead.

**Comment by SijmenHuizenga** [comment]
Scheduling a job every n mondays is not supported. You can read [here](https://github.com/dbader/schedule/pull/364#issuecomment-731644873) in more details why.

(yes, this should be in the docs. I will add it there)
