### ISSUE TITLE
Schedule on a specific day from() to ()

### ISSUE THREAD

**Issue by emiletab** [dbader/schedule#315]
I would like to know if it's possible to use the Scheduler module to schedule a task that starts at a certain time in a day let's say at('08:15:00'), and then I would like to run that job hourly on the same day till ('16:30:00') 

Regards!

**Comment by cuamckuu** [comment]
As far, as I know there is no built-in way to do it, but it's not hard to implement. 

Here is the code:

``` Python
import schedule
import time

class YourJob:
    job = None

    @staticmethod
    def start():
        YourJob.payload() # Execute exactly at 08:15:00
        YourJob.job = schedule.every().hour.do(YourJob.payload)

    @staticmethod
    def stop():
        if YourJob.job is not None:
            schedule.cancel_job(YourJob.job)

    @staticmethod
    def payload():
        # Here is your code for job
        print("Hello world")

schedule.every().day.at("08:15:00").do(YourJob.start)
schedule.every().day.at("16:30:00").do(YourJob.stop)

while True:
    schedule.run_pending()
    time.sleep(1)

```

**Comment by emiletab** [comment]
Thanks for the reply! 
I did the same thing but instead of using job i'm tagging every task with a unique tag, then i'm using the built-in cancel method to cancel that specific at task at a certain time!
