### ISSUE TITLE
Can I use sleep(60) instead of sleep(1)?

### ISSUE THREAD

**Issue by lucamanga** [dbader/schedule#316]
Can I use `sleep(60)` instead of `sleep(1)`?

**Comment by cuamckuu** [comment]
Hi, take look at [documentation of run_pending()](https://schedule.readthedocs.io/en/stable/api.html?highlight=run_pending#classes).

Here it is:

> Please note that it is intended behavior that run_pending() does not run missed jobs. For example, **if you’ve registered a job that should run every minute and you only call run_pending() in one hour increments then your job won’t be run 60 times in between but only once.**

So, if I'm not mistaken, your **time inside time.sleep() should be smaller than any of your registered event's time**.

**Comment by dar7man** [comment]
You can also use `sleep(scheduler.idle_seconds)`. It will wait just to run next scheduled job.
