### ISSUE TITLE
Kill or modify a schedule task

### ISSUE THREAD

**Issue by pawnies20** [dbader/schedule#32]
Hi and thank for your work: greatfull

Can you explain me how to kill, or modify a Schedule task?

Thank you

**Comment by dbader** [comment]
Hi @pawnies20. I'm not exactly sure what you mean by "kill or modify a schedule task" -- could you elaborate a bit more on what you want to achieve? Thanks.

**Comment by pawnies20** [comment]
Thank you, perfect !!!
A little question:
is it possible to cancel a specific schedule task?

Thank you very much
fred 

     Le Vendredi 9 janvier 2015 12h52, Dr. Di Prodi <notifications@github.com> a écrit :
   

 I did like this:   print ("Starting log...")
   schedule.every(20).minutes.do(get_weather_predictions)

   while 1:
      try:
         schedule.run_pending()
         time.sleep(2)
      except KeyboardInterrupt:
         print("Stopping scheduler")
         schedule.clear()
         print("Closing log")
         writer.close()
         break

**Comment by pawnies20** [comment]
Schedule.clear() works well, many thanx
But if i want to canceled a specific job what can i do?
schedule.cancel_job() or by returning schedule.CancelJob   seems don't work with me?
Thank you

Fred 

     Le Vendredi 9 janvier 2015 14h41, severine fred <severine.fred@yahoo.fr> a écrit :
   

 Thank you, perfect !!!
A little question:
is it possible to cancel a specific schedule task?

Thank you very much
fred 

     Le Vendredi 9 janvier 2015 12h52, Dr. Di Prodi <notifications@github.com> a écrit :
   

 I did like this:   print ("Starting log...")
   schedule.every(20).minutes.do(get_weather_predictions)

   while 1:
      try:
         schedule.run_pending()
         time.sleep(2)
      except KeyboardInterrupt:
         print("Stopping scheduler")
         schedule.clear()
         print("Closing log")
         writer.close()
         break

**Comment by pawnies20** [comment]
to dbader:

I only want to canceled a specific Schedule task.
Robomotic solution works fine but delete all active tasks

"Hi @pawnies20. I'm not exactly sure what you mean by "kill or modify a schedule task" -- could you elaborate a bit more on what you want to achieve? Thanks."

**Comment by pawnies20** [comment]
Please, help me !!!
Thanx

**Comment by dbader** [comment]
Hi @pawnies20 ,

you could do something like this:

```python
def job_that_executes_once():
    # Do some work ...
    return schedule.CancelJob

schedule.today.at('10:30').do(job_that_executes_once)
```

Basically you let the job cancel itself the first time it executes.

(Linking this to #33)
