### ISSUE TITLE
How to use library in custom event System.

### ISSUE THREAD

**Issue by lSh4dowl** [dbader/schedule#321]
So I want to use the library in my custom Event System, but sadly it doesn't seem to be made for that.
schedule.every().monday,tuesday, ... is very awkward for example. Sadly I don't finde the Docs to be very useful, so I couldn't find out if there is a way to call something like:
schedule.every().day(int day) where day is 0-6 representing monday to sunday.

Also something like weekly, monthly and yearly would be helpful.
Or a constructor, where you could do something like:
`_event = schedule.event`
`_event.at(Year, Month, Day, Hour, Minute, Second)`
or `_event.daily(Hour, Minute, Second)`
or `_event.weekly(Day, Hour, Minute, Second)`
`_event.repeat = True`
`_event.place()`

The lib is indeed very human readable, but in my opinion very hard to embed in a System.
Or am I just doing it wrong ?

**Comment by SijmenHuizenga** [comment]
Hi! We just picked up the conversation about this in #446.
