### ISSUE TITLE
Invalid syntax error

### ISSUE THREAD

**Issue by tntpower10** [dbader/schedule#328]
I'm getting a syntax error when i try to do this:
`schedule.every()day.at("00:05").do(message_check)`

I imported schedule correctly, and i couldn't find anything to fix this in the docs or anywhere else.

**Comment by aaditkamat** [comment]
@tntpower10, you have forgotten to include a "." between `every()` and `day`. You can see from the docs that the statement is `schedule.every().day.at("10:30").do(job)`. Anyways the dot is required because `day` is a property of the `Job` object returned by `schedule.every()`.

**Comment by tntpower10** [comment]
Thank you very much this worked!
