### ISSUE TITLE
Apply Hacktoberfest label to issues

### ISSUE THREAD

**Issue by aaditkamat** [dbader/schedule#329]
@dbader, will you be willing to accept contributions to this repository as part of [Digital Ocean's Hacktoberfest](https://hacktoberfest.digitalocean.com/details)?

**Comment by ansin218** [comment]
The Hacktoberfest website says: 

> PRs can be made to any public repo on GitHub, not only the ones with issues labeled Hacktoberfest. If a maintainer reports your pull request as spam or behavior not in line with the project’s code of conduct, you will be ineligible to participate.

My interpretation of this would be even if Dan does not label any issues, it will still count as long Dan does not mark anyone's contribution as spam.

**Comment by aaditkamat** [comment]
> My interpretation of this would be even if Dan does not label any issues, it will still count as long Dan does not mark anyone's contribution as spam.

Yes, you are right about that. My idea was that issues assigned the 'Hacktoberfest' label would more likely be noticed.

**Comment by SijmenHuizenga** [comment]
Good idea! We can do that. I've added a reminder in my agenda on october first 2021 to do this. 

Closing this for now as hacktoberfest is still many months away.

If you are reading this in October 2021 and there are no labels, feel free to ping me :ping_pong:.
