### ISSUE TITLE
Trouble Installing Schedule on RaspberryPi

### ISSUE THREAD

**Issue by dinahcodes** [dbader/schedule#333]
I want to transfer my twitter bot (https://github.com/clevergirldinah/Dinosaur-News-Bot) to my raspberry pi 3. the pi came with python 2.7 installed. i created a virtual environment, activated it, installed python 3.5, then used pip install schedule. when i return to the folder containing the bot (still in the virtual environment base) and try to execute the bot with python3 bot.py it says "Import Error: no module named schedule". i entered the Python 3.5 interactive help() to get a list of modules and there's one called sched but no module called schedule. tried pip install schedule again but it says requirement already satisfied.

**Comment by bradinator** [comment]
If you are using python 3.X,  you need to install using Pip3.  So the command would be `pip3 install schedule`
