### ISSUE TITLE
question: support multiple time every day 

### ISSUE THREAD

**Issue by yurenji** [dbader/schedule#335]
I wonder does the library support scheduling a task to run at multiple times every day, i.e. : 

`schedule.every().day.at("10:00, 12:00, 16:00").do(job)`

If not, is there a plan to support the feature?

**Comment by yurenji** [comment]
related issue: https://github.com/dbader/schedule/issues/298

**Comment by dbader** [comment]
Sure, just do this:

```python
schedule.every().day.at("10:00").do(job)
schedule.every().day.at("12:00").do(job)
schedule.every().day.at("16:00").do(job)
```
