### ISSUE TITLE
Using variables for time input.

### ISSUE THREAD

**Issue by Spinnaay** [dbader/schedule#34]
Hi,

I don't know if this belongs here so sorry if it's in the wrong place! Loving the scheduler though. 

Quick question, I would like to use variables to remotely change the times for the schedule. Something like 

time1 = "08:00"
schedule.every().day.at("%s").do(job) % (time1)

However, I just can't get it to work, which ever way round I try the string configuration and explanation marks. 

Any help would be greatly received. 

Thanks

T

**Comment by dbader** [comment]
Hi @Spinnaay,

try this: 

```python
time1 = "08:00"
schedule.every().day.at("%s" % time1).do(job)
```

Hope this helps :)

**Comment by Spinnaay** [comment]
Thanks, perfect.
