### ISSUE TITLE
Scheduling with respect to public holidays

### ISSUE THREAD

**Issue by bschumac** [dbader/schedule#340]
Hi, I use the weekdays option to repeat code quite a lot. However, I think an optimization would be possible taking the public holidays into account. I know this is dependend on the country/state the user is running the code in. So maybe dependend on a geographic coordinate? I see this as a long term goal.

**Comment by SijmenHuizenga** [comment]
Hi, Public holidays are out of scope for this library. Schedule is meant to be a simple solution for simple scheduling task. Public holidays are far from simple :wink:. As you already noted, holidays change per country/state/province/region, and they also change over time. Calculating when a public holiday takes place is not... straight forward at all. Just take a look at [python-holidays](https://github.com/dr-prodigy/python-holidays) to see how complex this really is. Let's keep schedule focussed on scheduling relatively often occuring tasks.
