### ISSUE TITLE
The job never stops

### ISSUE THREAD

**Issue by nor500** [dbader/schedule#341]
I am new to Python. I want to implement the schedule module in my script. According to the docs to run a job only once is like this:
'''
def job_that_executes_once():
    # Do some work ...
    return schedule.CancelJob

schedule.every().day.at('22:30').do(job_that_executes_once)
while True:
    schedule.run_pending()
    time.sleep(1)
'''
My problem is that in this way my script never stops. How can I make the script to stop after executing the job? Thanks for your help!

**Comment by Parkbro** [comment]
Return something from job that executes once and have it change the while True to False then it will stop after it's run.

**Comment by nor500** [comment]
Thank you. I will do that.
