### ISSUE TITLE
can we customize like picking cron value as */15 * * * * an argument and schedule jobs

### ISSUE THREAD

**Issue by thammaneni** [dbader/schedule#342]
i have specific cron jobs as different intervals like 

0 2,14 * * *

0,15,30,45 * * * *

is there any way to pass as an argument to schedule module/package ?

**Comment by SijmenHuizenga** [comment]
At the moment that's not possible to configure schedule using cron syntax.

**Comment by SijmenHuizenga** [comment]
Closing this, let's continue tracking this in #283
