### ISSUE TITLE
Ensure script is not already executing

### ISSUE THREAD

**Issue by Exosylver** [dbader/schedule#343]
I'm running this schedule to run a script called TGForwarder.py:
`import schedule
import time
import TGForwarder
def job():
        TGForwarder.run()
schedule.every(25).seconds.do(job)
while True:
        schedule.run_pending()
        time.sleep(1)`
Is there a way to ensure that after the next 25 seconds are up, if the previous run through of TGFowarder.py is still running, it will pass (skip the execution of the script and check again the next time around) the script on that time around?

**Comment by mondwan** [comment]
I am new to this project. Answer here may not be correct.

If TGForwarder.run() is kind of a blocking process, the schedule cannot be go on at all. Therefore, the problem you raise will never happend

If TGForwarder.run() is kind of a non-blocking process, I think the best strategy will be extending TGForwarder.run() such that it can stop running twice yourself. Or, You may try to override the Job.should_run & Job.run(). But, you still need to tell the Job when to stop, and when to start from TGForwarder

**Comment by KnottA** [comment]
I'm wondering about this too...

**Comment by SijmenHuizenga** [comment]
That's right! This library executes jobs on a single thread. If you need to run jobs in a separate thread, take a look at [the parallel execution documentation](https://schedule.readthedocs.io/en/stable/parallel-execution.html). If you need more advanced multithreading you might be better off using APSchedule instead.
