### ISSUE TITLE
can I dynamically change the interval

### ISSUE THREAD

**Issue by raako71** [dbader/schedule#349]
Can I use a dynamic variable to set the interval?

**Comment by raako71** [comment]
solved by looking at api
schedule.cancel_job(job)
schedule.every(period).minutes.do(job)

**Comment by raako71** [comment]
This actually failed. Trying to cancel a job from within a job didn't work. Workaround was to close script and reopen it

**Comment by rbrasga** [comment]
Yes, you can.
```
JOB_TAG="my job"

def job():
  my code...
  schedule.clear(JOB_TAB)
  schedule.every().day.at("06:03").tag(JOB_TAG).do(job)

schedule.every().day.at("02:57").tag(JOB_TAG).do(job)
while True:
   schedule.run_pending()
   sleep(1)
```
