### ISSUE TITLE
Find the number of active jobs?

### ISSUE THREAD

**Issue by SanojkumarNK** [dbader/schedule#352]
HI, 
   how i can find the number of active jobs in the scheduler ?.  I want to know because of what reason schedule is not working after some time.
**_Scenario_** :-  I Am running a program in aws with different jobs that is mentioned in same .py file. But after 2-3 hours program will stop processing till that it will run properly.. I tried 3 times, it is happening same thing...

**Comment by SijmenHuizenga** [comment]
Schedule always executes 1 job at the time. Schedule can't tell you if a job is running. You can add a boolean variable within your job to keep track of weather or not it is running.
