### ISSUE TITLE
Do a job every 4:30 hours,

### ISSUE THREAD

**Issue by eshk12** [dbader/schedule#353]
Hello, I want to use Function X every 4:30 hours,
What is the best option to do that, instand of convert hours to minutes?

schedule.every(4).hour.minutes(30).do(X)

**Comment by skokado** [comment]
How about like below?
`schedule.every(4 * 60 + 30).minutes.do(X)`

**Comment by eshk12** [comment]
I've already did that, I've looking for 4and half hour option.
