### ISSUE TITLE
`schedule.every(2).mondays.do(job)`

### ISSUE THREAD

**Issue by alfiepates** [dbader/schedule#354]
If I call `schedule.every(2).monday.do(job)`, schedule returns an intervalError:

````raise IntervalError('Use mondays instead of monday')```

This would imply that `schedule.every(2).mondays.do(job)` is valid, however: 

```AttributeError: 'Job' object has no attribute 'mondays'```

Is this an oversight, or is calling `schedule.every(2).mondays.do(job)` not supported by `schedule`?

**Comment by dan-cummings1** [comment]
Looks like anything outside of the interval `1` throws this exception but no `*days` appear to exist as properties of the class.

https://schedule.readthedocs.io/en/stable/api.html#schedule.Job

**Comment by jbvsmo** [comment]
Let's be honest. This library has too many holes for it to be used for anything other than a cute daily scheduler. This is not just an oversight but a prove no one uses it for real projects.

This assertion makes no sense. You really want the thing to sound like english that you need to enforce the "s" at the end of every attribute?

I'm working on legacy code with this lib and I might just replace it with something else that actually works.

**Comment by dan-cummings1** [comment]
Agreed, we moved away from using this and simply built out our jobs to let K8s cron jobs handle this for us.

Not looking back.

**Comment by SijmenHuizenga** [comment]
Yes, scheduling a job every n mondays is not supported. You can read [here](https://github.com/dbader/schedule/pull/364#issuecomment-731644873) in more details why.
