### ISSUE TITLE
schedule every minute schedules every 61 seconds

### ISSUE THREAD

**Issue by microprediction** [dbader/schedule#355]
Scheduling every minute leads to drift. The job is called at 36 seconds past the hour, then 37, then 38 and so forth.

**Comment by aekazitt** [comment]
Is this caused by your delay?
For example...
```
schedule.every().minute.do(job)
while True:
  try:
    schedule.run_pending() # 60 Seconds
    time.sleep(1)                   # 1 Second
  except KeyboardInterrupt:
    break
```

Perhaps use `schedule.idle_seconds()`
```
schedule.every().minute.do(job)
while True:
  try:
    schedule.run_pending()
    time.sleep(schedule.idle_seconds())
  except KeyboardInterrupt:
    break
```

**Comment by rajsid1** [comment]
This worked fine:
```
while True:
  schedule.run_pending()
  time.sleep(max((schedule.idle_seconds() - 1),0))
```

**Comment by Hantuch** [comment]
Hello, the solution helped in reducing drifts, but it seems the scheduler didn't took the function run-time into consideration (my function was I/O bound, took 0.7-0.8 s) and still caused drifts

Am I correct about that?
