### ISSUE TITLE
How to run job immediately?

### ISSUE THREAD

**Issue by zfz** [dbader/schedule#36]
Hi, I set my job to run every several seconds like: "schedule.every(t).seconds.do(func)".

Then I find that the job wait to run until t seconds. So how can I make it to run immediately? Thanks.

**Comment by blakev** [comment]
I believe if you add a `.run()` on the end of your schedule call, it will execute it right away and add it for rescheduling.

See [here](https://github.com/dbader/schedule/blob/master/schedule/__init__.py#L281-L287)

**Comment by zfz** [comment]
@blakev Thanks. It works.
