### ISSUE TITLE
run a python script 

### ISSUE THREAD

**Issue by sbhadade** [dbader/schedule#360]
```import schedule
import time
import data_utils

def job():
    data_utils.py

schedule.every(5).minutes.do(job)
# schedule.every().hour.do(job)
# schedule.every().day.at("10:30").do(job)
# schedule.every(5).to(10).minutes.do(job)
# schedule.every().monday.do(job)
# schedule.every().wednesday.at("13:15").do(job)
# schedule.every().minute.at(":17").do(job)

while True:
    schedule.run_pending()
    time.sleep(1)
```
getting this error

" data_utils.py
AttributeError: module 'data_utils' has no attribute 'py'"

**Comment by knowsuchagency** [comment]
That's not how you run code from another module; it's not a problem with this library

**Comment by aravindra1989** [comment]
import schedule
import time

def job():
    print("I'm working...")

schedule.every(1).minutes.do(job)
while True:
    schedule.run_pending()
    time.sleep(1)

Getting below error:

" partially initialized module 'schedule' has no attribute 'every' (most likely due to a circular import)"

**Comment by 07pepa** [comment]
You idealy need import everything once.... so you have one file that imports  data_utils and your scripts
and alsi import schedule then you just use schedule.every(1).minutes.do(job) in modules

please retract this issue and fix your code

**Comment by ricardodacosta** [comment]
May I ask how would one define a function to run a python script (test.py) within the same directory of lets say the scheduler.py script?
