### ISSUE TITLE
my own datetime.now

### ISSUE THREAD

**Issue by GreatQWERTY** [dbader/schedule#362]
Good day, I had to slightly redo your scheduler for yourself, adding
def __init __ (self, dt = None):
        self.jobs = []
        self.dt = dt

and below everywhere, change the string
datetime.datetime.now ()
to
self.dt.now ()
where self.dt is my class

class myclock:
   __dt= datetime.datetime(2020, 01, 01, 12, 30)

def now(self):   return self.__dt

could you add the ability to execute not only in system time

google translated

**Comment by kenahoo** [comment]
I second this request, it would be very helpful for running simulations, where the clock is not the real time of the world but rather the time in some simulated environment.

**Comment by 07pepa** [comment]
there is workaround https://github.com/clarete/forbiddenfruit

**Comment by SijmenHuizenga** [comment]
Hi there! The goal of this library is to provide super simple scheduling functionality. I believe customized time can be considered quite advanced. Therefore this won't be added.
