### ISSUE TITLE
Getting Error:"partially initialized module 'schedule' has no attribute 'every' (most likely due to a circular import)"

### ISSUE THREAD

**Issue by aravindra1989** [dbader/schedule#363]
import schedule
import time

def job():
    print("I'm working...")

schedule.every(1).minutes.do(job)
#schedule.every().hour.do(job)
#schedule.every().day.at("10:30").do(job)
#schedule.every(5).to(10).minutes.do(job)
#schedule.every().monday.do(job)
#schedule.every().wednesday.at("13:15").do(job)
#schedule.every().minute.at(":17").do(job)

while True:
    schedule.run_pending()
    time.sleep(1)

Error: partially initialized module 'schedule' has no attribute 'every' (most likely due to a circular import)

I am using python 3.8.2 version

**Comment by nok** [comment]
Hello @aravindra1989 ,

I also tested your script with Python 3.8 and got no errors. How did you use this script? Did you create the file in a module called `schedule`, e.g. `schedule/script.py`?
