### ISSUE TITLE
module schedule installed but not working in python

### ISSUE THREAD

**Issue by Z3r0Sh3ll** [dbader/schedule#365]
Python visual studio code
Hi
i have a problem right here ... in visual studio code when i  add import schedule 

Its color turns red ....

( Note : I can't use the Pip package )

That's why I have to install the Pip 3 package

then 

pip3 install schedule  ===> but installed

and still not working

**Comment by nok** [comment]
Hello @Z3r0Sh3ll ,

do you execute your scripts with `python filename.py`? If so, you can try to install `schedule` by using the following command:

```bash
python -m pip install schedule
```
