### ISSUE TITLE
Job does not write logs as expected

### ISSUE THREAD

**Issue by NicknameSoHard** [dbader/schedule#366]
### Summary
I handle schedule logger results and log it with my:

> 2020-04-27 13:17:15 INFO | Running job Every 1 minute do task_name() (last run: 2020-04-27 13:16:15, next run: 2020-04-27 13:17:15)
> 2020-04-27 13:18:15 INFO | Running job Every 1 minute do task_name() (last run: 2020-04-27 13:17:15, next run: 2020-04-27 13:18:15)
> 2020-04-27 13:19:15 INFO | Running job Every 1 minute do task_name() (last run: 2020-04-27 13:18:15, next run: 2020-04-27 13:19:15)

Why "next run" print time now? I think next run must be the time to next job running or must be renamed like "start time". It is unexpected message because its write log when job already works, so this message does not makes sense. Next execution job time would be more useful.

**Comment by SijmenHuizenga** [comment]
Logging has changed a bit since this was submitted. Currently:
```
import schedule
import logging
import time

logging.basicConfig()
schedule_logger = logging.getLogger('schedule')
schedule_logger.setLevel(level=logging.DEBUG)

def foo():
    print("Hello, Logs")

schedule.every().second.do(foo)

schedule.run_all()
time.sleep(3)
schedule.run_pending()

```
outputs:
```
DEBUG:schedule:Running *all* 1 jobs with 0s delay inbetween
DEBUG:schedule:Running job Job(interval=1, unit=seconds, do=foo, args=(), kwargs={})
Hello, Logs
DEBUG:schedule:Running job Job(interval=1, unit=seconds, do=foo, args=(), kwargs={})
Hello, Logs
```

The `last run` and `next run` are no longer shown. If you feel that is a problem you are welcome to create a new issue.
