### ISSUE TITLE
Return Flask jsonify response of schedule.jobs

### ISSUE THREAD

**Issue by phanlp** [dbader/schedule#367]
I am currently using the Python Schedule library in a Flask app and would like to return a jsonify response of my schedule.jobs. Schedule.jobs returns a default list of all the jobs in my schedule. Schedule.jobs returns a list of class objects (a list of [schedule.Job objects](https://schedule.readthedocs.io/en/stable/_modules/schedule.html#Job)).

I'm aware that the Flask JSON library does not allow you to jsonify a list. I have tried json dumps but got the following error: TypeError: Object of type Job is not JSON serializable.

How can I return a jsonify response of my list of class objects? See below for code:
`
>>> import schedule
>>> import time

>>> def geeks():
...     print("Shaurya says Geeksforgeeks")
... 
>>> def good_luck():
...     print("Good luck!")
... 
>>> def work():
...     print("Study hard work harder")
... 
>>> schedule.every(5).seconds.do(geeks)
Every 5 seconds do geeks() (last run: [never], next run: 2020-05-04 11:12:41)
>>> schedule.every(10).seconds.do(work)
Every 10 seconds do work() (last run: [never], next run: 2020-05-04 11:13:07)
>>> schedule.every(15).seconds.do(good_luck)
Every 15 seconds do good_luck() (last run: [never], next run: 2020-05-04 11:13:25)
>>> schedule.jobs
[Every 5 seconds do geeks() (last run: [never], next run: 2020-05-04 11:12:41), Every 10 seconds do work() (last run: [never], next run: 2020-05-04 11:13:07), Every 15 seconds do good_luck() (last run: [never], next run: 2020-05-04 11:13:25)]

>>> print(type(schedule.jobs))
<class 'list'>

>>> print(type(schedule.jobs[0]))
<class 'schedule.Job'>

>>> print(schedule.jobs[0])
Every 5 seconds do geeks() (last run: [never], next run: 2020-05-04 11:12:41)

>>> schedule_list = []
>>> for items in schedule.jobs:
...     schedule_list.append(items)
... 
>>> schedule_list
[Every 5 seconds do geeks() (last run: [never], next run: 2020-05-04 11:12:41), Every 10 seconds do work() (last run: [never], next run: 2020-05-04 11:13:07), Every 15 seconds do good_luck() (last run: [never], next run: 2020-05-04 11:13:25)]

>>> print(type(schedule_list[0]))
<class 'schedule.Job'>

>>> print(json.dumps(schedule_list))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/linda/opt/miniconda3/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Users/linda/opt/miniconda3/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/linda/opt/miniconda3/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/linda/opt/miniconda3/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Job is not JSON serializable
`

I have also tried JSON pickle, however the encode results look different. I would like the return to be a jsonify string like this:

Every 5 seconds do geek() (last run: [never], next run: 2020-05-04 16:58:45)
Every 5 seconds do work() (last run: [never], next run: 2020-05-04 16:58:49)

However, I'm getting this:
`
>>> for item in schedule.jobs:
...     print(item)
... 
Every 5 seconds do geek() (last run: [never], next run: 2020-05-04 16:58:45)
Every 5 seconds do work() (last run: [never], next run: 2020-05-04 16:58:49)
>>> for item in schedule.jobs:
...     schedJSON = jsonpickle.encode(item, unpicklable=False)
...     sched.append(schedJSON)
... 
>>> sched
['{"at_time": null, "interval": 5, "job_func": {"__annotations__": {}, "__doc__": null, "__module__": "__main__", "__name__": "geek", "__qualname__": "geek", "__wrapped__": null}, "last_run": null, "latest": null, "next_run": "2020-05-04 16:58:45.669355", "period": null, "scheduler": {"jobs": [null, {"at_time": null, "interval": 5, "job_func": {"__annotations__": {}, "__doc__": null, "__module__": "__main__", "__name__": "work", "__qualname__": "work", "__wrapped__": null}, "last_run": null, "latest": null, "next_run": "2020-05-04 16:58:49.000268", "period": null, "scheduler": null, "start_day": null, "tags": [], "unit": "seconds"}]}, "start_day": null, "tags": [], "unit": "seconds"}', '{"at_time": null, "interval": 5, "job_func": {"__annotations__": {}, "__doc__": null, "__module__": "__main__", "__name__": "work", "__qualname__": "work", "__wrapped__": null}, "last_run": null, "latest": null, "next_run": "2020-05-04 16:58:49.000268", "period": null, "scheduler": {"jobs": [{"at_time": null, "interval": 5, "job_func": {"__annotations__": {}, "__doc__": null, "__module__": "__main__", "__name__": "geek", "__qualname__": "geek", "__wrapped__": null}, "last_run": null, "latest": null, "next_run": "2020-05-04 16:58:45.669355", "period": null, "scheduler": null, "start_day": null, "tags": [], "unit": "seconds"}, null]}, "start_day": null, "tags": [], "unit": "seconds"}']
`

**Comment by KMouratidis** [comment]
1. Edit your post to make the code readable. Use the `preview` feature from GitHub (it helps looking a bit into Markdown)
2. Newer versions of flask (e.g. the 1.0.3 that I have) allow you to jsonify lists. E.g.  `jsonify([1,2,3])`
3. You should focus a bit more on core Python and reading exceptions. The error `TypeError: Object of type Job is not JSON serializable` is very clear: you cannot serialize `Job` to JSON. And you shouldn't want to pickle it either. 
4. Doesn't `str(job) for job in jobs` do exactly what you need?

**Comment by nok** [comment]
Hello @phanlp ,

you have to serialize the job instances by yourself. And it's not difficult. Hav a look at the current `repr` method: https://github.com/dbader/schedule/blob/master/schedule/__init__.py#L224-L261

You can use the following snippet to collect all relavant information:

```python
def serialize(job):
    def format_time(t):
        return t.strftime('%Y-%m-%d %H:%M:%S') if t else '[never]'

    if hasattr(job.job_func, '__name__'):
        job_func_name = job.job_func.__name__
    else:
        job_func_name = repr(job.job_func)
    args = [repr(x) for x in job.job_func.args]
    kwargs = ['%s=%s' % (k, repr(v))
              for k, v in job.job_func.keywords.items()]
    call_repr = job_func_name + '(' + ', '.join(args + kwargs) + ')'

    return dict(
        interval=str(job.interval),
        unit=str(job.unit[:-1] if job.interval == 1 else job.unit),
        call_repr=str(call_repr),
        timestats=dict(
            last_run=format_time(job.last_run),
            next_run=format_time(job.next_run)
        )
    )
```

You can apply the new method to all registered jobs:

```python
report = list(map(serialize, schedule.jobs))
```

And the result can be serialized and returned as a JSON string:

```python
import json

print(json.dumps(report, indent=2))

# [
#   {
#     "interval": "1",
#     "unit": "minute",
#     "call_repr": "runjob_a()",
#     "timestats": {
#       "last_run": "[never]",
#       "next_run": "2020-05-24 17:40:58"
#     }
#   },
#   {
#     "interval": "2",
#     "unit": "minutes",
#     "call_repr": "runjob_b()",
#     "timestats": {
#       "last_run": "[never]",
#       "next_run": "2020-05-24 17:41:58"
#     }
#   }
# ]
```

Please don't forget to test the return values.

**Comment by phanlp** [comment]
Thanks @nok. I have implemented the serialize code in my other project. I was wondering would you know why my `last_run` always returns "never"? Even though I run my tasks at a specific schedule at a certain time. It is running in a thread.
