### ISSUE TITLE
My job does not run everyday.

### ISSUE THREAD

**Issue by tfeng7** [dbader/schedule#368]
Hi all,
My job is needed to run at 22:50 every day. But I found, actually, it runs every other day. 
My script looks like:
```
def runjob():
    # do something

if __name__ == '__main__':
    if debugMode:
        runjob()
    else:
        schedule.every().day.at("22:50").do(runjob)
        while True:
            schedule.run_pending()
            mn = int(time.strftime("%M", time.gmtime()))
            if mn % 10 == 0:
                print("EnsForecast monitering at %s" %
                      time.strftime("%Y-%m-%d %H:%M", time.gmtime()))
            if debugMode:
                time.sleep(1)
            else:
                time.sleep(60)
```

For example, the job runs well on May 06, but nothing happened on May 07. 
```EnsForecast monitering at 2020-05-07 22:30
EnsForecast monitering at 2020-05-07 22:40
EnsForecast monitering at 2020-05-07 22:50
EnsForecast monitering at 2020-05-07 23:00
EnsForecast monitering at 2020-05-07 23:10
EnsForecast monitering at 2020-05-07 23:20```

Can anyone help me?

**Comment by MikeDoes** [comment]
Are you sure that it is running every other day? I think it only executes once because of the werid way you structured your while loop

**Comment by tfeng7** [comment]
> Are you sure that it is running every other day? I think it only executes once because of the werid way you structured your while loop

Dear MikeDoes,
I'm sure it's running every other day. Maybe I should try some other way for the loop. Thanks for your reply.

**Comment by nok** [comment]
Hello @MikeDoes ,

I recommend to simplify your script in several methods and decrease the seconds to a value lower than 60.

```python
def runjob():
    print("I'm making something.")  # print/log something


def _print_time():
    now = datetime.now()
    if now.minute % 10 == 0:
        now_str = now.strftime("%Y-%m-%d %H:%M")
        print("EnsForecast monitering at %s" % now_str)


def develop():
    runjob()


def main():
    schedule.every().day.at("22:50").do(runjob)
    while True:
        _print_time()
        schedule.run_pending()
        time.sleep(30)  # wait 30 seconds


if __name__ == '__main__':
    if DEBUG_MODE:
        develop()
    else:
        main()
```

**Comment by MikeDoes** [comment]
Thanks @nok, it's @tfeng7 's script however :)

**Comment by Kubci** [comment]
I have very similar problem, I don't know if it might be related here, but I need to launch functionality at the end of each hour (schedule.every().hour.at("59:59").do(self.stream_fragmentation_restart)).  But if the restart lasts more then one second, then the trigger is set not within current hour but the next one. So in the end some of the calls are every hour and others are every two hours.

**Comment by SijmenHuizenga** [comment]
Hi there! Closing this issue as this seems to be resolved. Feel free to comment if something is still unclear.
