### ISSUE TITLE
session() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by braincantu** [dbader/schedule#369]
only my login is refreshed 1 time

![imagen](https://user-images.githubusercontent.com/61814425/83084330-3bd61300-a04e-11ea-8d97-433c2d61a74c.png)
![imagen](https://user-images.githubusercontent.com/61814425/83084343-45f81180-a04e-11ea-81c9-fa8437c2f4fb.png)

**Comment by 07pepa** [comment]
this will newer work and it is pebkach .... you do not have instance nor constructor.... so create instance
like
```
instance=Login_Api()
shedule.every(10).seconds.do(instance.session()
```
