### ISSUE TITLE
'module' object has no attribute 'every'

### ISSUE THREAD

**Issue by atuljain** [dbader/schedule#37]
schedule.every(10).minutes.do(job)
AttributeError: 'module' object has no attribute 'every'

My full code

import schedule
import time

def job():
        print("Helo Wolrd ")

schedule.every(10).minutes.do(job)
schedule.every().hour.do(job)

while True:
        schedule.run_pending()
        time.sleep(1)

**Comment by dbader** [comment]
Sorry but I can't reproduce this.
Did you install `schedule`? (`pip install schedule`)

**Comment by atuljain** [comment]
yes, i installed schedule

**Comment by Xarphus** [comment]
Hello, I have the same problem. I did install schedule - once over pip and once over downloading the lib and install it manually (python setup.py install). When I attempt to start your example code I get the following message:     
schedule.every(10).minutes.do(job)
AttributeError: 'module' object has no attribute 'every'
I am using windows 7 - 64 bit system.

**Comment by WoLfulus** [comment]
how are you guys importing the library?

i mean...

    from schedule import * 
    import schedule

**Comment by Xarphus** [comment]
WoFulus, I am importing the library as in the example:

```import schedule
```

**Comment by dylwhich** [comment]
What's the output of this script?

    import schedule
    print(schedule.__doc__)
    print(dir(schedule))

**Comment by Xarphus** [comment]
The output ist:

'''None
['__builtins__', '__doc__', '__file__', '__name__', '__package__']'''

**Comment by sahinabi** [comment]
i think this happens if you name your python file "schedule.py"

**Comment by miknonny** [comment]
@sahinabi I had exactly same issue and this helped me solve it. i named my python file schedule.py

**Comment by christianbundy** [comment]
I'm an idiot.

**Comment by quapka** [comment]
@sahinabi Thanks, I was working on example for stackoverflow.. And in the rush I simply named it `schedule.py`.. Then after realizing it I renamed the file, however the copy `schedule.py` was still there. Well, quite funny five minutes..

**Comment by Katajam** [comment]
@sahinabi Thanks. I made the exactly same mistake.

**Comment by dbader** [comment]
I think this is worth adding to the FAQ at this point :) If anyone wants to go ahead and create a pull-request for that, please do. If not I'll do it when we get the next release ready.

**Comment by mayank113463** [comment]
chnage the name of your python file it will work for me ..schedule.py ---> schedule123.py

**Comment by ingenuity2k** [comment]
yes, silly us, naming the module `schedule.py`, what an outlandish thing to do :)
You might want to consider adding this tidbit to the readme as well; most people probably only bother to read that, since many repos don't offer a FAQ. Nice touch to include that though btw.

**Comment by ymd007** [comment]
That what! Thankyou, so much.

**Comment by mikemaer1990** [comment]
Heads up if by chance you are using Flask -- and your route is called schedule -- it also causes this same issue!

**Comment by ManojTupe** [comment]
import time
import datetime
import schedule

def task():
    print("Task after each minute gets eexecuted")
    print("Current time is :",datetime.datetime.now())

def main():
    print("Insdie main function")
    print("Schedular starts...")

    schedule.every(1).minutes.do(task)

    while True:
        schedule.run_pending()
        time.sleep(1)

if __name__ == "__main__":
    main()

![Screenshot (4)](https://user-images.githubusercontent.com/98576410/152371554-43a9eb69-090b-4fc1-b469-6d5faf247e0b.png)



please help me what can i do

**Comment by ManojTupe** [comment]
Check the code once / type once again

**Comment by ggarcz1** [comment]
run this in the command line:
_pip install schedule && pip install pytz_
