### ISSUE TITLE
Need help scheduling Notification every 1 second.

### ISSUE THREAD

**Issue by samibaig17** [dbader/schedule#371]
I am using pync module to show the notification but I want the notification to be shown every 1 second. code is working but it is not showing me notification every 1 second.

`from pync import Notifier`
`import schedule`
`import time`

`def main(): 
	 pass`
	 
`schedule.every(1).seconds.do(main,Notifier.notify(message='Drink Water Please',title ='Drinking water is good for health',appIcon="/Users/mirzasamibaig/Downloads/{python}/water.ico")
)`

**Comment by rbrasga** [comment]
Are you looking for something like this?

```
from pync import Notifier
import schedule
import time

def notify_me():
  Notifier.notify(message='Drink Water Please',title ='Drinking water is good for health',appIcon="/Users/mirzasamibaig/Downloads/{python}/water.ico")

schedule.every().second.do(notify_me)
while True:
  schedule.run_pending()
  time.sleep(1)
```
