### ISSUE TITLE
Jobs keep running, non-stop

### ISSUE THREAD

**Issue by GabrieleAnsaldo** [dbader/schedule#373]
I set up my schedule as follows:

```
def job():
   my code

schedule.every().day.at("06:03").do(job)
schedule.every().day.at("09:56").do(job)
schedule.every().day.at("13:47").do(job)
schedule.every().day.at("17:15").do(job)
schedule.every().day.at("20:34").do(job) 
schedule.every().day.at("23:46").do(job)
schedule.every().day.at("02:57").do(job)
    
while True:
   schedule.run_pending()
   sleep(1)
```

However, the job sometimes takes 1 hour and some other time it takes 10 hours. The problem arises when the job takes the longest (10 hrs). As soon as it ends it seems like the schedule decides to run again all the jobs it has been missing within those 10 hours. 

How can I fix that?

Usually, the job needs to sleep for 10 hours when a boolean becomes True otherwise if the boolean is False the job takes around 1 hour. Is it possible to fix this issue by adjusting the infinite loop as follows?

```
while True:
   if my_boolean == True:
      sleep(10*60*60)
      my_boolean == False
   else:
      schedule.run_pending()
      sleep(1)
```

**Comment by rbrasga** [comment]
@GabrieleAnsaldo Here's a dead simple fix.

Reset the scheduler at the end of each job.

If a job takes 10 hours, it won't run the ones that overlapped.
If a job takes 1 hour, it has no impact.

`
JOB_TAG="my job"

def job():
  my code...
  schedule.clear(JOB_TAB)
  schedule_jobs()

def schedule_jobs():
  schedule.every().day.at("06:03").tag(JOB_TAG).do(job)
  schedule.every().day.at("09:56").tag(JOB_TAG).do(job)
  schedule.every().day.at("13:47").tag(JOB_TAG).do(job)
  schedule.every().day.at("17:15").tag(JOB_TAG).do(job)
  schedule.every().day.at("20:34").tag(JOB_TAG).do(job) 
  schedule.every().day.at("23:46").tag(JOB_TAG).do(job)
  schedule.every().day.at("02:57").tag(JOB_TAG).do(job)
    
schedule_jobs()
while True:
   schedule.run_pending()
   sleep(1)
`
