### ISSUE TITLE
Jobs scheduled every day get skipped on certain days

### ISSUE THREAD

**Issue by rbrasga** [dbader/schedule#375]
I have a strange problem where jobs scheduled everyday will not get executed that day.

Jobs scheduled on specific days can take up to 12 hours to complete, and when that specific-day job completes, it's as if the every-day jobs were never scheduled/pending.

```
schedule.every().day.at("09:00").do(job1)
schedule.every().day.at("16:00").do(job2)
schedule.every().day.at("16:05").do(job3)
schedule.every().monday.at("05:00").do(job4)
schedule.every().tuesday.at("05:00").do(job5)

while True:
	schedule.run_pending()
	time.sleep(1)
```

**Comment by SijmenHuizenga** [comment]
Hi! Thanks for reporting this. As you are mentioning long-running jobs starting in the afternoon I have the strong suspicion it is the same problem as described in #304. Closing this as a duplicate.
