### ISSUE TITLE
Schedule Python with while loop

### ISSUE THREAD

**Issue by vin86** [dbader/schedule#376]
in my python bot i want use schedule module with a while loop. I want that every 60 seconds, while loop execute one iteration and not all loop. How can i do?

This is my code

```
 def job():
        count = 0
        variable1 = json.loads(requests.get(url).text)
        while count < (len(variable1['deals']['dr'])):
            ***example code to execute***
            count+=1

    schedule.every(60).seconds.do(job)

    while True:
        schedule.run_pending()
        time.sleep(1)
```

**Comment by Oracking** [comment]
You can make your job a generator function. This way, every time it is called, it executes one iteration and yields. You can [read](https://www.programiz.com/python-programming/generator) about generators or [watch](https://www.youtube.com/watch?v=bD05uGo_sVI) a tutorial that nicely explains how to use them.

Here's a solution that makes the job a generator function:

```python
def job():
    count = 0
    variable1 = json.loads(requests.get(url).text)
    while count < (len(variable1['deals']['dr'])):
       ***example code to execute***
        count+=1
        yield

iterable_job = job()
schedule.every(60).seconds.do(lambda: next(iterable_job))

while True:
    schedule.run_pending()
    time.sleep(1)
```

**Comment by weizzmann** [comment]
**### help me, please. when i run the given code:**

import schedule
import time


def job():
    count = 0
    while count < 3:
        count += 1
        yield count


iterable_job = job()
schedule.every(3).seconds.do(lambda: next(iterable_job))

while True:
    schedule.run_pending()
    time.sleep(1)

### **_throws the following error_**

Traceback (most recent call last):
  File "shedule.py", line 20, in <module>
    schedule.run_pending()
  File "/home/alex/PycharmProjects/messenger/venv/lib/python3.6/site-packages/schedule/__init__.py", line 592, in run_pending
    default_scheduler.run_pending()
  File "/home/alex/PycharmProjects/messenger/venv/lib/python3.6/site-packages/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/home/alex/PycharmProjects/messenger/venv/lib/python3.6/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/home/alex/PycharmProjects/messenger/venv/lib/python3.6/site-packages/schedule/__init__.py", line 491, in run
    ret = self.job_func()
  File "shedule.py", line 16, in <lambda>
    schedule.every(3).seconds.do(lambda: next(iterable_job))
StopIteration
