### ISSUE TITLE
support weekday

### ISSUE THREAD

**Issue by flamz3d** [dbader/schedule#378]
schedule is super useful and handy, thank you.

here's a suggestion.

`schedule.every().weekday.at("07:00").do(start_coffee_machine)`

syntactic sugar yes, but would be nice,

**Comment by frek818** [comment]
If this is syntactic sugar what is the the supported alternative? I'm trying to execute a function every weekday.

**Comment by gavinkalika** [comment]
+1

**Comment by SijmenHuizenga** [comment]
Hi! This feature request is being tracked in #129.

If you feel like this request is different you are welcome to commend and we can re-open :)
