### ISSUE TITLE
同一时刻创建了两个任务之疑问。

### ISSUE THREAD

**Issue by ShaoMingya** [dbader/schedule#379]
比如下面这种情况，同一时间安排了两个不同的任务，且两个任务需要优先级关系，
```
schedule.every().day.at("10:47:30").do(job_close_video)
schedule.every().day.at("10:47:30").do(job_open_music)
```
目前测试结果，是按照创建计划任务的顺序依次执行的。
请问：
是否从原理上也是这样处理的？
未来更新有没有考虑对这种情况加上优先级参数?
未来是否可查询某个时刻或某个时间段的任务列表？

**Comment by SijmenHuizenga** [comment]
Hi there! Thanks for your interest in Schedule. The main language for this repo is English. Please open a new issue in English if your question is still relevant.
