### ISSUE TITLE
More Complex Scheduling

### ISSUE THREAD

**Issue by AlexIzydorczyk** [dbader/schedule#38]
Hi, 

Thanks for making this, it is a great tool. I am wondering whether anyone has or is planning to build out functionality for complex intervals such as "last Saturday of every month"?

Thanks,
Alex

**Comment by dbader** [comment]
Thank you :)

I don't think we should do that for the reasons stated in #73 and #82.

Closing this so we can keep the tracker clean of loose ends. Feel free to follow up (or make a separate issue) with more questions/discussion 😃
