### ISSUE TITLE
job.next_run is not set correctly when the scheduler is scheduled seconds BEFORE the current time

### ISSUE THREAD

**Issue by RNPhelan** [dbader/schedule#381]
The below code schedules the scheduler for the NEXT Saturday at 11:15:13 even when the code is executed at 11:15:02 on a Saturday (11 seconds before the time scheduled).

***

import schedule
import datetime

def my_job():
    print("Job executing!")

def main():
    job = schedule.every().saturday.at("11:15:13").do(my_job)
    print(job.next_run)

    print("done!")

if __name__ == "__main__":
    main()

**Comment by SijmenHuizenga** [comment]
Thanks for reporting this! 

This bug has been fixed in #337 and released in 1.0.0. A unit test to cover this case has also been added: 

https://github.com/dbader/schedule/blob/32a14006dc3aa875bd37c1aeb65de7b526941961/test_schedule.py#L217-L224
