### ISSUE TITLE
object has no attribute 'fridays' but 'Job' object has no attribute 'fridays'

### ISSUE THREAD

**Issue by MichaelSchmidt82** [dbader/schedule#387]
Hi,

I'd like to report an issue!  It goes like this:

```
foo = lambda: print('hi')
schedule.every().friday.do(foo)
Every 1 week do <lambda>() (last run: [never], next run: 2020-09-25 18:54:53)
```

```
schedule.every(2).friday.do(foo)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/schedule/__init__.py", line 330, in friday
    raise IntervalError('Use fridays instead of friday')
schedule.IntervalError: Use fridays instead of friday
```

```
schedule.every(2).fridays.do(foo)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'Job' object has no attribute 'fridays'
```

I suppose I'm doing something wrong but I thought I would raise this as an issue since the syntax and semantics seems straight forward.

**Comment by SijmenHuizenga** [comment]
Hi! Thanks for raising this! 

Schedule does not support scheduling jobs every n weekday. Read [here](https://github.com/dbader/schedule/pull/364#issuecomment-731644873) why this is.

Yes, the error message totally wrong and should be updated. Just created #433 to track this.
