### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by MartinThoma** [dbader/schedule#392]
Are there plans to add type annotations or stub files for mypy?

I've written an [article about type annotations](https://medium.com/analytics-vidhya/type-annotations-in-python-3-8-3b401384403d) if you need one :-) 

A related topic is the Python 2.7 support. Stub files can be added without affecting any runtime, but they are harder to maintain (as they are extra files - I'm not sure how often `schedule` is refactored / new functionality is added).

Having Python 3.6+ would allow schedule to use a [very nice annotation syntax](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep526). Generally speaking, this type of type annotations makes code way easier to read.

**Comment by SijmenHuizenga** [comment]
Yes! After we drop python 2.7 support (see #409) we can do this!

**Comment by SijmenHuizenga** [comment]
Python 2.7 has been dropped! Is anyone willing to implement this and create a pr?

**Comment by MartinThoma** [comment]
Nice!

I can add a first WIP-PR this evening. The lowest supported Python version now is 3.6, right?

**Comment by SijmenHuizenga** [comment]
Awesome!! Yes, 3.6 is the lowest supported version for this library.

**Comment by MartinThoma** [comment]
Would adding https://pypi.org/project/typing-extensions/ for Python 3.6 and 3.7 for having [Literal](https://www.python.org/dev/peps/pep-0586/) be acceptable?

**Comment by MartinThoma** [comment]
Other question: I've just noticed that schedule does not use [`black`](https://pypi.org/project/black/). Do you use another autoformatter?

**Comment by SijmenHuizenga** [comment]
Let's start of without adding typing-extensions. One of the cool things of this library is it's lack of dependencies, if we can I would like to keep it that way.

Formatter is flake8.

**Comment by MartinThoma** [comment]
> Let's start of without adding typing-extensions

Ok :ok_hand: 

> Formatter is flake8.

I only know how to use flake8 as a linter (complaining about formatting), not how to use it as a formatter (fixing formatting)

**Comment by SijmenHuizenga** [comment]
ah yes, I have no idea how to do auto-formatting using flake8, I just manually fix the errors :laughing: Never took the time to figure that out. If you do, sharing would be much appreciated :heart:

**Comment by MartinThoma** [comment]
In this case I can warmly recommend using black :-) 

I grew into liking black because it does NOT allow customization. Code formatted by black always looks the same. As you cannot customize it, you don’t need to discuss it. It just solves the issue of conflicting styles and arguments around it. Black is maintained by the Python Software Foundation and likely the most commonly adopted auto formatter for Python.

Black is compatible with PEP8 and a typical set of Flake8 (IIRC, Flake8 has some conflicting rules, depending on what you use ... and, of course, lots of plugins).

The thing where I needed to get used to:

* Black always uses `"`, except when you would need escaping (e.g. `'He said: "I told you so"'` will not be touched by black)
* Black tries to make diffs minimal. In some cases, I don't like that so much. But I love having minimal diffs :-)
