### ISSUE TITLE
Run in 5 minutes?

### ISSUE THREAD

**Issue by sumoway** [dbader/schedule#40]
Is there a way to schedule a job to run in a specified amount of time?  e.g., I would like to schedule a job to run 5 minutes from now.

**Comment by sumoway** [comment]
I guess what I'm looking for is `schedule.once().at('10:30').do(...)` or `schedule.once().in(5).minutes.do(...)`

**Comment by cfrco** [comment]
Hello, Sumoway,

One possible solution is use `CancelJob`.  Just return `CancelJob` at your job function.
And the job would be removed from job list.
You cloud follow https://github.com/dbader/schedule/pull/15 to find more details.

**Comment by yoway** [comment]
Thank you cfrco!

**Comment by dbader** [comment]
This is also in the FAQ now.
