### ISSUE TITLE
Timezone Reset After Asynchronous Task

### ISSUE THREAD

**Issue by aekazitt** [dbader/schedule#406]
When I set it up as so...
```
import time
import schedule 
from tasks.one import task_1
from tasks.two import task_2

schedule.every(20).seconds.do(task_1)
schedule.every(5).minutes.do(task_2)

while True:
  try:
    schedule.run_pending()
    idle = max(schedule.idle_seconds(), 0)
    time.sleep(idle)
  except KeyboardInterrupt:
    schedule.clear()
    break
```

I would get this type of behavior in my logs...
  
```
Next scheduled task at 2021-01-01 02:10:40.197428
[INFO] Task 1
Next scheduled task at 2021-01-01 02:11:00.746995
[INFO] Task 1
Next scheduled task at 2021-01-01 02:11:21.675689
[INFO] Task 1
Next scheduled task at 2021-01-01 02:11:42.360605
[INFO] Task 1
Next scheduled task at 2021-01-01 02:12:02.974911
[INFO] Task 1
Next scheduled task at 2021-01-01 02:12:23.423114
[INFO] Task 1
Next scheduled task at 2021-01-01 02:12:44.007639
[INFO] Task 1
Next scheduled task at 2021-01-01 02:13:04.686992
[INFO] Task 1
Next scheduled task at 2021-01-01 02:13:25.679852
[INFO] Task 1
Next scheduled task at 2021-01-01 02:13:46.263566
[INFO] Task 1
Next scheduled task at 2021-01-01 02:14:06.874801
[INFO] Task 1
Next scheduled task at 2021-01-01 02:14:18.229551
[INFO] Task 2
Next scheduled task at 2020-12-31 19:19:18.459096
```

And then the wait time between tasks jumped up from 20 seconds to 25000+ seconds.

The asynchronous task being performed in `task_2` is `tortoise-orm` and I obtained the event-loop
using `asyncio.get_event_loop()` method.

Is there a way to bypass this timezone reset that resets the timezone (+7:00) to UTC and making the whole schedule off?

**Comment by SijmenHuizenga** [comment]
Hi!

Schedule uses the default python `datetime` for all the timing calculations. So somewhere something is causing the `datetime` package to think it moved to a different timezone. There is no way in schedule to enter a custom `datetime` or custom timezone. Dealing with timezone's is quite advanced so it is out of scope for this project.

However, in this case your best bet would be to set the timezone before scheduling the first task. If the timezone is at +7:00 at the start of the program (and stays that way) schedule will keep working.

Hope this helps!

**Comment by aekazitt** [comment]
It really helps! I actually decided to run everything at UTC and then repeatedly resets my timezone as well.
