### ISSUE TITLE
Dropping Python 2.7 and 3.5

### ISSUE THREAD

**Issue by SijmenHuizenga** [dbader/schedule#409]
Over a year ago python 2 was deprecated. I think it's time to drop support for Python 2 in the next version. Only supporting Python 3 is nice because it allows us to integrate python-3 only features like coroutines and type-hinting without workarounds. It is also a bit useless to keep supporting something that less and less people are using. Python 2 software can keep on using the current version of the library. It is stable and won't break.

What do you think?

**Comment by hugovk** [comment]
Python 3.5 is also EOL and could be dropped too (3.6 has f-strings!)

Here's the pip installs for schedule from PyPI for December 2020, showing very low numbers for 2.7 and 3.5:

| category | percent | downloads |
|----------|--------:|----------:|
| 3.7      |  38.15% |   193,357 |
| 3.6      |  31.53% |   159,808 |
| 3.8      |  17.04% |    86,365 |
| 3.5      |   4.31% |    21,826 |
| null     |   3.94% |    19,986 |
| 2.7      |   2.90% |    14,722 |
| 3.9      |   2.08% |    10,520 |
| 3.4      |   0.05% |       247 |
| 3.10     |   0.00% |        18 |
| 2.6      |   0.00% |         2 |
| Total    |         |   506,851 |

Source: `pip install -U pypistats && pypistats python_minor schedule --last-month`

**Comment by SijmenHuizenga** [comment]
Thanks @hugovk for sharing up those stats.

36,548 downloads (for 2.7 and 3.5) is a lot of people :open_mouth:. We should document how to install an older version of this package for those users.

I didn't realize 3.5 has reached end of life as well, have updated the title to also drop 3.5

**Comment by hugovk** [comment]
Not every download is a single person, CIs and mirrors and who knows what else are also counted.

And single digit percentages are really low. For comparison, 22% of the downloads of pip itself are for 2.7, about 14 million(!), but pip is dropping Python 2.7 (and 3.5) in this month's v21.0 release.

Anyway, it's good this project is using `python_requires`, updating this will also help pip install the last compatible version of schedule:

https://github.com/dbader/schedule/blob/705f3730e40fd1a4451dedcf28de510aa5c86212/setup.py#L55
