### ISSUE TITLE
Job scheduling for more than 1 hour

### ISSUE THREAD

**Issue by arshpreetsingh** [dbader/schedule#41]
schedule.every().hour.do(job) 
only take (1) as argument, Please correcet me if I am wrong?

Do I need some hack to schedule it for two hours?

**Comment by dylwhich** [comment]
I believe you want:

    schedule.every(n).hours.do(job)

This will run the job every `n` hours. Using `every().hour` implies every hour, whereas `every().hours` can run on a multiple of hours.
