### ISSUE TITLE
add callback that trigers on_idle_seconds_change

### ISSUE THREAD

**Issue by 07pepa** [dbader/schedule#410]
With interuptable sleep documented [here](https://github.com/dbader/schedule/issues/388)

there is possibility to use idle_seconds() to wait/sleep pasively for whol and not poll every X seconds if it is right time

this is already possibe with current implementation with one edgecase... if we are adding task during runtime of "scheduling loop" durring sleep/wait and is scheduled to execute within that sleep it would be missed.

this is advantageous when you have long periods of sleep

ps there will be [time problems](https://www.youtube.com/watch?v=-5wpm-gesOY) that are also present in current implementation and please open link you will have a laught :D

**Comment by SijmenHuizenga** [comment]
Hi @07pepa! Doing a callback requires some kind of multithreading, which is out of scope for this library. [This comment](https://github.com/dbader/schedule/issues/92#issuecomment-746625130) explains the rationale in a bit more detail. If you need something like callbacks I would recommend taking a look at APSchedule.

Let me know if you have any more questions!

ps, YES, that's a legendary video from Tom :)

**Comment by 07pepa** [comment]
you are right... and in most cases this callback would be unnecesseary... maybe close this...?
