### ISSUE TITLE
next_run() report wrong Date/Time

### ISSUE THREAD

**Issue by WillianBR** [dbader/schedule#411]
I'm having a situation where my JOB run too fast and after it is runned, my call to **next_run()** report the one that was gone! 

Eg:

- Before run: _2021-01-08 11:35:00_
 - After run: _2021-01-08 11:35:00_
 - Idle Seconds: _-5.777853_

My JOB taked **3.4326s** to run, because there wasn't too much data to process.  So the next run was supposed to be "**2021-01-09 11:35:00**".

The "**_schedule_next_run()**" is protected, so I can't call to force a update when idle_seconds are less than one second.

To do it I have to patch the code and that's not a pretty solution.  Any future update (docker build image will do that).

So, Let's fix it?

Thanks!

**Comment by SijmenHuizenga** [comment]
Yes, Let's fix this! 

Can you share the piece of code that causes this? Especially the part where you call `schedule.ever().....` and the sleeping & `schedule.run_pending()` would be helpful.

**Comment by SijmenHuizenga** [comment]
Give no code was provided I assume the problem has been resolved. Feel free to open another issue if this is not the case.
