### ISSUE TITLE
how to skip debug output to console ?

### ISSUE THREAD

**Issue by AndKe** [dbader/schedule#413]
How can I avoid filling up the console with this job? 
```
schedule         INFO     Running job Every 0.3 seconds do check_door_status() (last run: 2021-01-11 17:11:47, next run: 2021-01-11 17:11:47)
schedule         INFO     Running job Every 0.3 seconds do check_door_status() (last run: 2021-01-11 17:11:47, next run: 2021-01-11 17:11:47)
schedule         INFO     Running job Every 0.3 seconds do check_door_status() (last run: 2021-01-11 17:11:47, next run: 2021-01-11 17:11:48)
```

**Comment by SijmenHuizenga** [comment]
Set the logging level of the `schedule` logger to `ERROR` to disable the `INFO` logs from the scheduler:
```
schedule_logger = logging.getLogger('schedule')
schedule_logger.setLevel(level=logging.ERROR)
```

Let me know if this helps!

**Comment by AndKe** [comment]
ok, I found 
```
import logging
logging.getLogger('schedule').propagate = False
```

It would be nice if one could filer by level per schedule (set level per schedule, or filter by tag)

**Comment by AndKe** [comment]
@SijmenHuizenga It does help, you beat me to answer my own question. Thanks,  
A per-schedule or per-task option would still be nice.

**Comment by SijmenHuizenga** [comment]
Our solutions were like seconds apart, that's quite a special thing ;)

The easiest way to achieve per-task or per-schedule logging is to disable the built-in logging and add your own logging lines to the jobs themselves. Take a look at [this annotation logging](https://schedule.readthedocs.io/en/latest/logging.html#customize-logging) example for maybe some inspiration ;)
