### ISSUE TITLE
Wrong next_run calculation

### ISSUE THREAD

**Issue by WoLfulus** [dbader/schedule#42]
I believe this line

https://github.com/dbader/schedule/blob/master/schedule/__init__.py#L325

is missing an 

    and self.interval == 1

because when you set for example:

    scheduler.every(2).days.at('12:00').do(job)

executing it after 12:00 will schedule next_run for the next 2 days, and executing it before 12:00 will schedule to the next day, breaking the 2-day rule

to see it happen just change 

    with mock_datetime(2010, 1, 6, 13, 16):

to

    with mock_datetime(2010, 1, 6, 10, 16):

here: https://github.com/dbader/schedule/blob/master/test_schedule.py#L192

**Comment by dbader** [comment]
Thanks for reporting this @WoLfulus! I'm on vacation at the moment but I will be able to look into this next week. If you want to go ahead and create a pull request with a fix (+ a test case) that would be fantastic :-)

**Comment by WoLfulus** [comment]
@dbader done ;)

**Comment by dbader** [comment]
Fixed in #43.
