### ISSUE TITLE
Odd and even weeks

### ISSUE THREAD

**Issue by Ventvo** [dbader/schedule#422]
I can't find any way to use schedule for odd and even weeks based events. Sorry if its already integrated and I am just dumm :) .

**Comment by SijmenHuizenga** [comment]
Schedule does indeed not support odd and even based events. This is quite a specific thing that doesn't fit that well in the library itself. The best way you can achieve this is by scheduling a job to run every week and check the week number in the job function.

**Comment by Ventvo** [comment]
"L" stands for odd and "S" stands for even.
![Screenshot_20210201-125954](https://user-images.githubusercontent.com/22612951/106456255-8e918580-648d-11eb-9564-78b9575869ad.jpg)

**Comment by Ventvo** [comment]
> Schedule does indeed not support odd and even based events. This is quite a specific thing that doesn't fit that well in the library itself. The best way you can achieve this is by scheduling a job to run every week and check the week number in the job function.

Thanks, I thought about that solution, but I wanted to check if it can be solved better way.
