### ISSUE TITLE
Change jobs while schedule is running

### ISSUE THREAD

**Issue by guruanshsingh** [dbader/schedule#423]
I am trying to add/remove jobs while the schedule is already running. Concrete example below:

At t=0
Schedule job A to run every 15 mins and job B to run every 60 minutes
I need to pull an API that gives me information about every job that needs to run. Assume this polling has to happen every 5 mins.
At t=5 minutes
I get an update from the API that job B needs to be canceled and job C with frequency 10 mins needs to be added.
How should I poll and update? If I cancel pending jobs and schedule again, then any jobs scheduled to run with period > 5 mins would never run.

**Comment by SijmenHuizenga** [comment]
```
def a():
  pass

def b():
  pass

def c():
  pass 

job_a = schedule.every(15).minutes.do(a)
job_b = schedule.every(60).minutes.do(b)

def poll_api():
  # do the polling
  schedule.cancel_job(job_b)
  job_c = schedule.every(10).minutes.do(C)

schedule.every(5).minutes.do(poll_api)

while True:
    schedule.run_pending()
    time.sleep(1)
```

>  If I cancel pending jobs and schedule again, then any jobs scheduled to run with period > 5 mins would never run.

The solution is to only cancel the jobs that need to be canceled, don't touch the others. You can use `cancel_job` to cancel a single job.
