### ISSUE TITLE
Task after task 

### ISSUE THREAD

**Issue by saveliyborkov** [dbader/schedule#428]
Hi, everyone!

I have two tasks and I’d like to run them every 30 minutes, but one after another.
Is there any solution?

thanks!

**Comment by SijmenHuizenga** [comment]
Schedule does not support sequential tasks but you can schedule 1 job and call both tasks from within: 

```
import schedule
import time

def task1():
   print("hi")

def task2():
  print("hello")

def job():
    task1()
    task2()

schedule.every(30).minutes.do(job)

while True:
    schedule.run_pending()
    time.sleep(1)
```
