### ISSUE TITLE
Simple document typo

### ISSUE THREAD

**Issue by pghpete** [dbader/schedule#431]
There is a misspelling in the documentation code examples on this page... [examples](https://schedule.readthedocs.io/en/stable/examples.html#pass-arguments-to-a-job)

Under the Cancel a Job section...
`shcedule.cancel_job(job)`
should be
`schedule.cancel_job(job)`

Thanks for your work on this very handy scheduling library!

**Comment by SijmenHuizenga** [comment]
Glad to hear you like the library! And thanks for bringing this up :+1:  This typo [has been fixed on the main branch](https://github.com/dbader/schedule/pull/426/files#diff-5311c1419ec81d9fdb5cbfdb6e595afcac980d90e3e508c34b592595564d386fL78) a few days ago and will be published as part of the next release.
