### ISSUE TITLE
Improve error message when scheduling job every n weekday

### ISSUE THREAD

**Issue by SijmenHuizenga** [dbader/schedule#433]
The following code:
```
schedule.every(2).friday.do(foo)
```
Results in the following error:
```
schedule.IntervalError: Use fridays instead of friday
```
The error message makes one believe that the code should be updated to:
```
schedule.every(2).fridays.do(foo)
```
:point_up: **is invalid code**. `fridays()` [is not supported by design](https://github.com/dbader/schedule/pull/364#issuecomment-731644873). 

Let's update the error message to reflect this.

**Comment by sosolidkk** [comment]
Hello, i'm looking forward to submit my first contribution. Can i get this one? What would be a proper error message?

**Comment by SijmenHuizenga** [comment]
Hi @sosolidkk Yes, you can go ahead!  I think the best way to do this is to change the error message in something more descriptive. Suggestions are welcome :wink: Maybe something along the lines of `scheduling jobs every n weeks is not supported`?

**Comment by sosolidkk** [comment]
Could be something like `For week days use only the interval equal to 1` since it's the only supported value? And we could to the same to the weekends since it contains the same message.

```python
    @property
    def saturday(self):
        if self.interval != 1:
            raise IntervalError("Use saturdays instead of saturday")
        self.start_day = "saturday"
        return self.weeks

    @property
    def sunday(self):
        if self.interval != 1:
            raise IntervalError("Use sundays instead of sunday")
        self.start_day = "sunday"
        return self.weeks
```
