### ISSUE TITLE
staggered  jobs -- 30 minute clock

### ISSUE THREAD

**Issue by electronhead** [dbader/schedule#440]
I was wondering if there was a simple way to do this with schedule:

An irrigation system needs to be active for say 20% of the time within 30 minute time periods. If there were a 30-minute clock, there would be an ON job at 00:00 and and OFF job at 06:00.

One way would be with three scheduled jobs:
```
schedule.every(30).minutes.at("00:00").do(ON)
schedule.every(1).hour.at("06:00").do(OFF)
schedule.every(1).hour.at("36:00").do(OFF)
```

Is there a way to do this with one OFF job? As in something like...
```
schedule.every(30).minutes.at("00:00").do(ON)
schedule.every(30).minutes.at("06:00").do(OFF)
```

I know that the second line produces an error (ScheduleValueError: Invalid time format for a minutely job), but maybe there is another way to collapse the three line solution into two liner with schedule.

**Comment by SijmenHuizenga** [comment]
Would something like this work?
```
def on():
  # turn it on
  schedule.every(6).minutes.do(off)

def off(): 
   # turn it off
  return schedule.CancelJob

schedule.every(30).minutes.do(on)
```

**Comment by electronhead** [comment]
That would do it for sure.

I was wondering if there was a way to do it with just the function calls. This is a nice solution though.

**Comment by SijmenHuizenga** [comment]
The simplest solution I can think of using only scheduling commands is: 
```
schedule.every().hour.at(":00").do(ON)
schedule.every().hour.at(":06").do(OFF)
schedule.every().hour.at(":30").do(ON)
schedule.every().hour.at(":36").do(OFF)
```
Downside of this solution is that if the program starts at 12:01, ON will only be triggered at 12:30. So in the 30-minute period between 12:01 and 12:31 there would be no pump power. In the earlier solution using `schedule.CancelJob` you could call `on()` at startup to ensure something like that doesn't happen.
