### ISSUE TITLE
No module named schedule.__main__; 'schedule' is a package and cannot be directly executed

### ISSUE THREAD

**Issue by joris-devdata** [dbader/schedule#447]
Hello,

This is the message i had from vs code debug. i have installed schedule 1.0.0 in a virtual env python 3.9.1 version. if i run it with jupyterlab, i have no problem.

I have checked that my python interpreter is correctly configured (Python 3.9.1 64-bit ('venvp39') and that scheduler is installed in my 'venvp39' folder.

What should I do with VSC (version1.54.1) please ? i haven't found a solution on google or stackoverflow for the moment.

Thanks for your help ;-)
![image_490](https://user-images.githubusercontent.com/73476550/110843668-d97e9400-82a8-11eb-90dc-7dc0a3ed8c01.png)

**Comment by joris-devdata** [comment]
wrong image

**Comment by joris-devdata** [comment]
Works perfectly in jupyterlab
![image_491](https://user-images.githubusercontent.com/73476550/110844125-527deb80-82a9-11eb-935d-d906fc27973c.png)

**Comment by SijmenHuizenga** [comment]
Hi @joris-devdata, I'm glad to hear you are giving schedule a try. The problem you are experiencing seems to be caused by visual studio code since schedule works fine in jupterlab. I think you will be getter much better help by asking the VSC community, either on Github, Reddit or Stackoverflow.

**Comment by joris-devdata** [comment]
Allright, i will. As soon as i have an answer, i will share ;-)
