### ISSUE TITLE
Does your program freeup memory every after a scheduled event?

### ISSUE THREAD

**Issue by codewithpatch** [dbader/schedule#449]
I have been searching if after every job, your program frees up memory or does the memory usage stack up as your program runs?

**Comment by SijmenHuizenga** [comment]
The schedule library's memory usage does not increase as it runs for a longer period of time. Schedule does not track the execution history. The memory usage after scheduling the jobs should be ~equal to the memory usage after a long period of time. Does this answer your question?

**Comment by codewithpatch** [comment]
Yes. This answers my question. Thanks!
