### ISSUE TITLE
TypeError: 'Job' object is not callable

### ISSUE THREAD

**Issue by adbuerger** [dbader/schedule#45]
Hello Daniel, I would really like to use schedule, but for me it only returns `TypeError: 'Job' object is not callable`:

```python
import schedule

def job():
    print("foo")

schedule.every(10).minutes().do(job)
```

I'm on Xubuntu 14.04, Python 2.7.6 and installed schedule via pip. Can you tell me what is going wrong here? Maybe it's just a simple mistake. Thank you very much for your help!

**Comment by dylwhich** [comment]
Don't call `minutes`, just do:

    schedule.every(10).minutes.do(job)

**Comment by adbuerger** [comment]
Dang :-/ no idea why I didn't see this... closed, of course! Thanks very much!

**Comment by dbader** [comment]
Argh, please ignore the accidental reference :)

Thanks for jumping in and answering this one @dylwhich! :)

**Comment by mohit1337** [comment]
Why not to make a better warning exception whenever everyone calls minutes as a method?
