### ISSUE TITLE
Get the return value of a scheduled function into a variable

### ISSUE THREAD

**Issue by AmitKehat** [dbader/schedule#451]
Hi,

When print the returned value of scheduled function:
```
schedule.every(1).minute.do(func, arg1, arg2)
```

I am getting:
```
"Every 1 minute do func(arg1, arg2)"
```

I would like to get the real return value of the function.
Can it be done?

Thanks,
Amit

**Comment by bsll0828** [comment]
`
import time
import datetime

import schedule


def now():
    return datetime.datetime.now()


def one_plus_one():
    return 1 + 1


job1 = schedule.every(10).seconds
job1.job_func = now

job2 = schedule.every(10).seconds
job2.job_func = one_plus_one

# job3 = ...
# job4 = ...
# ...

schedule.jobs.append(job1)
schedule.jobs.append(job2)
# schedule.jobs.append(job3)
# schedule.jobs.append(job4)
# ...

[job.run() for job in schedule.jobs]

while True:
    should_run_jobs = (job for job in schedule.jobs if job.should_run)
    for job in sorted(should_run_jobs):
        result = job.run()

        print(result)

    time.sleep(1)

`

**Comment by bsll0828** [comment]
**Like this**

```
import time
import datetime

import schedule


def now():
    return datetime.datetime.now()


def one_plus_one():
    return 1 + 1


job1 = schedule.every(10).seconds
job1.job_func = now

job2 = schedule.every(10).seconds
job2.job_func = one_plus_one

# job3 = ...
# job4 = ...
# ...

schedule.jobs.append(job1)
schedule.jobs.append(job2)
# schedule.jobs.append(job3)
# schedule.jobs.append(job4)
# ...

[job.run() for job in schedule.jobs]

while True:
    should_run_jobs = (job for job in schedule.jobs if job.should_run)
    for job in sorted(should_run_jobs):
        result = job.run()

        print(result)

    time.sleep(1)

```

**Comment by AmitKehat** [comment]
Thank you so much, this is very helpful.

I have a follow up question.
How can I make the same but with functions that has arguments?
In the 'regular' method I run it like this:
`schedule.every(1).minute.do(func, arg1, arg2)`
but in our case here, I don't have the 'do' part.
I am getting and error regarding the arguments when I am trying to defile:
`job1.job_func = func, arg1 = 'x', arg2 = 'y'`

Thanks,
Amit

**Comment by bsll0828** [comment]
just try this
```
job1.do(any_func, arg1, arg2)
```
and deprecated
```
job1.job_func = any_func
```

**Comment by AmitKehat** [comment]
Thank you for your answer. It worked for me.

Another follow up question:
if I want to schedule 2 functions, and use the returned value of the first function as an argument to the second function:
```
val = func1(arg1, arg2)
val2 = func2(val)
```

How can I do that?

**Comment by SijmenHuizenga** [comment]
There is no built-in way to support sharing data between scheduled jobs. The next best thing would be to store the data in some shared variable in either a class variable or global variable.

If you have any more questions feel free to open a new issue.
