### ISSUE TITLE
Run a job until a certain time [until]

### ISSUE THREAD

**Issue by Chrisjack56** [dbader/schedule#452]
I see on this GitHub that there is an until function within the code but, I cannot utilize it. I currently have the most up to date version of schedule but it will not work regardless of how I format the time within the 'until( )'. Can you please advise? I have attached a snippet of the traceback below:

Traceback (most recent call last):
  schedule.every(5).minutes.until("18:30").do(run_threaded, <function>)
  AttributeError: 'Job' object has no attribute 'until'

**Comment by SijmenHuizenga** [comment]
This is because no release has happened since the `until` was added. Thanks for reminding me that I should make a new release. Will do so somewhere this weekend.

**Comment by Chrisjack56** [comment]
Just wanted to follow up and see if there was an update on the release

**Comment by SijmenHuizenga** [comment]
See #455 :)

**Comment by Chrisjack56** [comment]
Thank you very much
