### ISSUE TITLE
AttributeError: 'Job' object has no attribute 'until'

### ISSUE THREAD

**Issue by andres-stack** [dbader/schedule#456]
I'm getting this error every time I try to use the until method. I even tried copying and pasting the code from the example and I still get this error. please help.

**Comment by SijmenHuizenga** [comment]
The `.until` method was added in yesterday's release. Can you check if you are using the latest version (1.1.0)? If you installed scheduling using pip, run the following command?
```
pip show schedule                                                                                                                                                               
``` 
It should output
```
Name: schedule
Version: 1.1.0
```

**Comment by andres-stack** [comment]
I have version 1.0.0. How do I get the latest version?

> The `.until` method was added in yesterday's release. Can you check if you are using the latest version (1.1.0)? If you installed scheduling using pip, run the following command?
> 
> ```
> pip show schedule                                                                                                                                                               
> ```
> 
> It should output
> 
> ```
> Name: schedule
> Version: 1.1.0
> ```

**Comment by andres-stack** [comment]
> The `.until` method was added in yesterday's release. Can you check if you are using the latest version (1.1.0)? If you installed scheduling using pip, run the following command?
> 
> ```
> pip show schedule                                                                                                                                                               
> ```
> 
> It should output
> 
> ```
> Name: schedule
> Version: 1.1.0
> ```

I have version 1.0.0 How would I install the latest version?
