### ISSUE TITLE
Schedule ImportError: cannot import name 'repeat'

### ISSUE THREAD

**Issue by vba34520** [dbader/schedule#457]
Platform: Windows 10

When I run the example code of [Use a decorator to schedule a job](https://schedule.readthedocs.io/en/stable/examples.html#use-a-decorator-to-schedule-a-job), it cause `Schedule ImportError: cannot import name 'repeat'`.

```shell
pip list | grep schedule
```
```
schedule 1.0.0
```

Looking forward to your reply!

**Comment by SijmenHuizenga** [comment]
Hi! The repeat decorator was added in the 1.1.0 release :)
