### ISSUE TITLE
Enhancement: can we get a every().working_day().do() ?

### ISSUE THREAD

**Issue by Wissperwind** [dbader/schedule#459]
Hi,
I need do schedule a job every monday to friday at 10:00.
Is there alread an option I missed? Can we get one?

Thanks!

**Comment by anthonyzutter** [comment]
**I did this:**
```
import datetime
day = datetime.datetime.today().weekday()
if day < 5:
    #schedule
else:
    print("Weekend")
```

**Comment by OjasWadhwani** [comment]
While we can work on something like every().workday.do(), where the workday array in the [library](https://github.com/dbader/schedule/blob/master/schedule/__init__.py) can be as: 
`workdays = {
      "monday",
      "monday",
"monday",
"monday",
}`
I do not think schedule as a library is meant for that. Here is the doc link for reference: [when not to use a schdule](https://schedule.readthedocs.io/en/stable/#when-not-to-use-schedule)

**Comment by OjasWadhwani** [comment]
While we can work on something like every().workday.do(), where the new workdays array in the [library](https://github.com/dbader/schedule/blob/master/schedule/__init__.py) can be as:
`workdays = [ "monday", "tuesday", "wednesday", "thursday", "friday" ]`
I do not think schedule as a library is meant for that. Here is the doc link for reference: [when not to use a schdule](https://schedule.readthedocs.io/en/stable/#when-not-to-use-schedule)
Moreover, workdays as a parameter are defined different from different organisations.

**Comment by SijmenHuizenga** [comment]
Hi! You could run a job daily and skip the execution on saturdays and sundays. This would look like this:

```python
import schedule
import datetime

def job():
    # Monday is 0 and Friday is 4
    if datetime.datetime.today().weekday() > 4:
        return
    
    # do whatever needs to do
    pass

schedule.every().day.at("10:00").do(job)
```

If you have any more questions, feel free to open a new ticket :+1:

**Comment by Wissperwind** [comment]
Yes, I can use this workaround. I think it would improve the library to add it, but if you don't agree. It's your library.
But thanks for the open discussion.
