### ISSUE TITLE
Error Scheduling

### ISSUE THREAD

**Issue by redkad** [dbader/schedule#461]
I was wondering if there's a way to schedule a function to run from a particular time to another time and repeat the same process each day?

**Comment by SijmenHuizenga** [comment]
I'm not exactly sure what you mean. Could you elaborate a bit more?

If i'm taking a wild guess you want to run a job every second/minute/hour between some period of time every day. This can be achieved by running a job continuously and check if the current time is in the period that it needs to run at.

This example shows how to run a job every hour between 09:00 and 17:00:

```
import schedule
import datetime

def hourly():
    hour_now = datetime.datetime.now().hour
    if hour_now >= 9 and hour_now < 17:
        print("I run every hour between 09:00 and 17:00")
    pass

schedule.every().hour.do(hourly)

print(schedule.next_run())
```

**Comment by redkad** [comment]
Thank you.
