### ISSUE TITLE
Can't start the scheduled jobs properly

### ISSUE THREAD

**Issue by DoomCreature** [dbader/schedule#462]
Hi there,

I'm trying to use schedule to runs two simple task in the background on a small project.
And I don't know how to start it properly.

My code:

schedule.py
```python
import threading, time, schedule

def run_continuously(interval=1):
    cease_continuous_run = threading.Event()

    class ScheduleThread(threading.Thread):
        @classmethod
        def run(cls):
            while not cease_continuous_run.is_set():
                schedule.run_pending()
                time.sleep(interval)
        continuous_thread = ScheduleThread()
        continuous_thread.start()
        return cease_continuous_run

def sunday():
    now = datetime.now().strftime('%Y-%m-%d')
    if now == 'any chosen date':
        do my thing ...
    else:
        print('print a message')

def hour_job():
    now = datetime.now().strftime('%Y-%m-%d')
    if now == 'another chosen date':
        do my other thing ...
    else:
        print('print another message')

schedule.every().sunday.at("14:00").do(sunday)
schedule.every(2).hours.do(hour_job)

cease_continuous_run = run_continuously()
time.sleep(1)
stop_run_continuously.set() # even if I comment this line the jobs do not start

# and when I did an attempt from outside like:

from diary.alert.schedule import run_continuously
run_continuously()

# or with sunday() or hour_job()  not the three at same time of course! each job runs twice O,O
```

Just one more thing.
I did noticed when I comment the line
```python
stop_run_continuously.set()
```

and comment the external trigger
```python
from diary.alert.schedule import run_continuously
run_continuously()
```

save both files start the server then uncomment the external trigger and save the file the jobs run like they supposed to. Perfectly in harmony with the desired schedule.

I do thank in advance for any help!

**Comment by DoomCreature** [comment]
I do believe this is the answer:

On the file the start the program we should add the trigger for the schedule, like:

app.py

    from YourApp import create_app
    from YourApp.path.to.schedule import run_continuously

    app = create_app()

    if __name__ == '__main__':
        cease_continuous_run = run_continuously()

    # add the use_reloader and set it to false so jobs run only once
    app.run(debug=True, port=8001, host='localhost', use_reloader=False) 

Is it the right way to do it?

**Comment by SijmenHuizenga** [comment]
Looking at the code you shared, it seems the indenting got messed up a bit. Take a close look at [the example](https://schedule.readthedocs.io/en/latest/background-execution.html) and compare it with the code you have. You may notice  that `class ScheduleThread` is part of the `def run_continuously` function. Also, `continuous_thread = ScheduleThread` is not inside the `class ScheduleThread` block.

**Comment by DoomCreature** [comment]
> Looking at the code you shared, it seems the indenting got messed up a bit. Take a close look at [the example](https://schedule.readthedocs.io/en/latest/background-execution.html) and compare it with the code you have. You may notice that `class ScheduleThread` is part of the `def run_continuously` function. Also, `continuous_thread = ScheduleThread` is not inside the `class ScheduleThread` block.

Just a copy paste newbie mistake.
I didn't knew how to color the code so when I tried to edit it that happen _(if you're able to see the edit history will may notice that I did a lot of attempts on it)_.

But the doubt remains. Do you know if this is the right way to start the schedule jobs?

**Comment by SijmenHuizenga** [comment]
Ah I see, it is getting better and better! The indentation is almost perfect now.

Yes, this is a good way to start a background thread that runs scheduled jobs :+1:

**Comment by DoomCreature** [comment]
> Ah I see, it is getting better and better! The indentation is almost perfect now.
> 
> Yes, this is a good way to start a background thread that runs scheduled jobs +1

Thank you for your help @SijmenHuizenga
