### ISSUE TITLE
New Method to declare timezone: `tz()`

### ISSUE THREAD

**Issue by chrimaho** [dbader/schedule#470]
I would like to define the timezone when I would like my scheduler to run.

If we take this example:

```python
# No specified time zone. These will use the local timezone.
schedule.every().day.at("10:30").do(job)
schedule.every().wednesday.at("13:15").do(job)
schedule.every(2).days.at("17:47").do(job)
```

We can enhance it to add one more step to specify the required timezone.

```python
# Defined time zone.
schedule.every().day.at("10:30").tz("America/New_York").do(job)
schedule.every().wednesday.at("13:15").tz("Australia/Sydney").do(job)
schedule.every(2).days.at("17:47").tz("Europe/London").do(job)
```

The benefits of this would be very very helpful. Especially for multi-national companies who need something like this to work at a specified time in a specific timezone.

**Comment by rocky4546** [comment]
Currently schedule.py has no dependencies and can exists alone.  This fix adds multiple packages that are not part of the standard python install.  The question that should be asked is whether this file should now have required complexity.  It looks like the author build this file to not had dependencies.

**Comment by SijmenHuizenga** [comment]
Support for timezone in `.at()` has been added in 1.2.0 :tada:
