### ISSUE TITLE
Running scheduler script in background

### ISSUE THREAD

**Issue by TheTeraByte** [dbader/schedule#48]
Hi! I'm trying to use this package to run a task once every week. However, I have noticed that when I run my scheduler script (currently set to running the task every 2 minutes for debugging) in the background the job does not happen. Does the script need to be always running in the foreground for the task to be executed, or was this package intended to provide fire-and-forget functionality? 

To further elaborate: suppose I run the scheduler script in the background, close the terminal, shut down my laptop and open it later can I still expect the weekly task to execute when Sunday comes around (just like cron can be relied on to behave so)?

**Comment by WoLfulus** [comment]
the script needs to keep running and updating in order to get jobs executed... 

for example:

    schedule.every(2).minutes.do(job)

this will schedule a job to execute every 2 minutes, but to get jobs executed you need to keep updating the schedule:

    while True:
        schedule.run_pending()
        time.sleep(1)

the run_pending function is the one that actually executes the scheduled jobs.

**Comment by TheTeraByte** [comment]
@WoLfulus Thanks a ton for the clarification! I have configured cron to run the script every time I start my laptop.
