### ISSUE TITLE
Run whole Jupyter Notebook

### ISSUE THREAD

**Issue by turbo1618** [dbader/schedule#490]
I am new to python coding and still learning a lot.

How can I schedule to run my entire Jupyter notebook? I would like to schedule my code to run every weekday at a certain time. 

Here is my normal process: I have 10-20 Jupyter notebooks open. After the stock market closes for the day, I go to each notebook and click "Cell" then "Run All". I have python code in 16 different cells that analyzes different data and prints charts.

I would like to have all these notebooks run automatically at a specific time of day.

What is the best way to "Run All" the code in my Jupyter notebook?

**Comment by SijmenHuizenga** [comment]
Hi! I think you best guess is to use a tool that is specifically made to run Jupyter notebooks on a schedule. This `schedule` library is used to run Python functions from within a Python program, not so much to execute external programs at a schedule. Maybe [this can help](https://stackoverflow.com/a/49510178/2328729)?
