### ISSUE TITLE
Is there a way to not having to hardcode the days in the schedule?

### ISSUE THREAD

**Issue by theopfr** [dbader/schedule#496]
I need to read the day, at which the job should run, out of a config file. Therefore I need a way to specify the day in the scheduler as an argument. For example like this:
```python
# how it could look like with a dynamic argument for the days:
schedule.every().day("monday").at("06:00").do(execute_job)

# vs. how I works right now with the day hardcoded: 
schedule.every().monday.at("06:00").do(execute_job)
```
I didn't find a way to do that. The only workaround that I can think of is by using ```eval()```:
```python
day = "monday"
eval(f"schedule.every().{day}('06:00').do(execute_job)")
```
As long as Im not missing anything, I think it would be nice if such a functionality is added.

**Comment by Wissperwind** [comment]
Would fit to my feature request to support cron tab expressions.

**Comment by SijmenHuizenga** [comment]
You could achieve dynamic days like this:

```python
day = 'monday'
getattr(schedule.every(), day).at('06:00').do(execute_job)
````
