### ISSUE TITLE
Using Schedule with a webserver in the same script

### ISSUE THREAD

**Issue by drixie** [dbader/schedule#498]
I have noticed Schedule does not work when it is in the same script with a webserver (e.g. main.py). I have tried both FastAPI and Eventlet with no success. 

I will appreciate any pointers on how to get this to work.

**Comment by SijmenHuizenga** [comment]
In most schedule examples, schedule runs on the main thread. I'm guessing that the webserver uses the main thread as well. You probably need to run schedule on a background thread, like [described here](https://schedule.readthedocs.io/en/stable/background-execution.html).
