### ISSUE TITLE
What timezone does the time refer to? 

### ISSUE THREAD

**Issue by MetzinAround** [dbader/schedule#516]
I've searched the docs and can't seem to find the answer. 

When using a time for a day, what is the time referencing if there's no way to specify a time zone? Is it UTC? PT? Knowing what the reference time is will help me know when to schedule my jobs to fire. 

`schedule.every().day.at("10:30").do(job)`  For instance, what is 10:30 referring to here?

**Comment by SijmenHuizenga** [comment]
Hi @MetzinAround, At the moment the schedule library uses naive [datetime](https://docs.python.org/3/library/datetime.html) objects, representing current local date and time. So in `.at("10:30")` the `10:30` is local time.  Hope this help!
