### ISSUE TITLE
Contributing to schedule

### ISSUE THREAD

**Issue by TheTeraByte** [dbader/schedule#52]
Hi! I've been using `schedule` for about a month or so now, and I think it's a great library. I was wondering if I could contribute to its development in any way? Any new features, documentation or tests to add?

**Comment by dbader** [comment]
Thanks @TheTeraByte, I'd love your help. I realize this is a super old question – but maybe you're still interested in working on schedule.

I'm putting together a ticket to discuss areas of improvement and things we'll want to focus on. You can find it here: https://github.com/dbader/schedule/issues/107

Closing this so we can keep the tracker clean of loose ends. Feel free to follow up (or make a separate issue) with more questions/discussion 😃
