### ISSUE TITLE
Running Asyncs

### ISSUE THREAD

**Issue by Rajdave69** [dbader/schedule#524]
How do I run Asyncs with this module? 
code - 
schedule.every().saturday.at("15:55").do(await reminder("Saturday", "test", "3"))

self.job_func = functools.partial(job_func, *args, **kwargs)
TypeError: the first argument must be callable

This is my error. I've tried multiple things but nothing works.

**Comment by JamesAib** [comment]
im having the same error no documentation or explanation seems to help

**Comment by SijmenHuizenga** [comment]
Async jobs are not yet supported.

**Comment by JamesAib** [comment]
I actually managed to make it use normal def ty anyway
