### ISSUE TITLE
TypeError 'Job' object is not callable when running schedule within class

### ISSUE THREAD

**Issue by denhua** [dbader/schedule#53]
Hi,

I need help with this code snippet. Below, I'm instantiating a schedule object within a class.
And from within the class I'm running my loop which I hope to run the scheduled job. It seems the "at" method won't accept the job I give it throwing a TypeError. Whereas running it every minute works fine.
In both cases assert statement does not fire. Can someone provide insight?

Thanks,
Dennis

``` python
import schedule
import time

class TestSchedule():

    def __init__(self):
        self.schedule = schedule

    def setup(self):
        ### WORKS ###
        # self.schedule.every(1).minutes.do(self.job)
        assert callable(self.job)
        ### DOESN'T WORK ###
        self.schedule.every().day().at("7:54").do(self.job)

    def job(self):
        print 'Job start at {0}'.format(time.strftime('%H:%M'))

    def loop(self):
        while 1:
            self.schedule.run_pending()
            print 'Sleeping for 10 sec'
            time.sleep(10)

if __name__ == '__main__':
    ts = TestSchedule()
    ts.setup()
    print 'Start schedule at {0}'.format(time.strftime('%H:%M'))
    ts.loop()

```

**Comment by WoLfulus** [comment]
i don't know if this could be the issue, but "day" is a proerty, not a function

try 

    self.schedule.every().day.at("7:54").do(self.job)

**Comment by denhua** [comment]
Thanks! You are correct.
        
self.schedule.every(1).days.at("8:35").do(self.job)

as works.
