### ISSUE TITLE
[request] Update pypi release

### ISSUE THREAD

**Issue by joe733** [dbader/schedule#530]
It's been over a year. Please create a new tagged release for PyPi

**Comment by maxnyman** [comment]
The current PyPi version of `schedule` doesn't have the TZ support

**Comment by jhellinckx** [comment]
Indeed, there is TZ support on master but not in the latest PyPi release (1.1.0). 
Would really appreciate a new release too!

**Comment by joe733** [comment]
https://pypi.org/project/schedule/1.2.0/
