### ISSUE TITLE
not able to use the schedule module in the Windows server 2012 r2 edition , 

### ISSUE THREAD

**Issue by sravanre** [dbader/schedule#535]
why I am not able to use the schedule module in the Windows server 2012 r2 edition , 
same code is working fine for me in the windows 10 desktop , 

But not in the windows server 2012

**Comment by beliaev-maksim** [comment]
there could be multiple differences in how time is treated on OSs
Windows Server 2012 is too old and EOL

You need to upgrade at least to Server 2019
