### ISSUE TITLE
Scheduler doesn't execute function within class (is it because it's not a first-class function)?

### ISSUE THREAD

**Issue by denhua** [dbader/schedule#54]
Hi,

I'm trying to schedule a set of jobs. The jobs are supposed to be taken from a config file but for this test I only need to simulate it.

The sample code below setups a list of jobs (I'm using "work" as my name for job) prior to setting up the scheduler. When I run the scheduler and pass in the function "pp" to "do" method the code below executes as expected. However, when I pass to "do" a function within the works list, whether self.sqr or inline definition of sqr or a lambda function, the code does not execute correctly.

What am I doing wrong? I want the function to be defined in the works list (that gets executed by "do") because I would like to define my scheduler to have no knowledge of the kind of work it will perform.

Thanks for any help,
Dennis

```python
import schedule
import time
import datetime

class TestSchedule():

    def __init__(self):
        self.schedule = schedule
        self.works = []
        self.setup_works()
        self.setup_schedule()

    def sqr(self, x):
        return x * x

    def setup_works(self):
        #def sqr(x):
        #    return x * x

        for num in range(24):
            self.works.append({
                'name': num,
                'func': self.sqr,
            })

    def run(self, interval=30, blocking=True):
        while True:
            if not blocking:
                break
            else:
                print 'Before run_pending()  -----------------------'
                self.schedule.run_pending()
                print '{0}: Sleeping ... ({1} sec)'.format(datetime.datetime.now(), interval)
                time.sleep(interval)

    def print_works(self):
        for work in self.works:
            print(work['name']),
        print

    def print_exec_works(self):
        for work in self.works:
            print(work['func'](work['name'])),
        print

    def setup_schedule(self):
        def pp(s):
            print(s),

        for work in self.works:
            sched = self.parse_work_schedule(work)
            if sched:
                #sched(pp, work['name'])
                sched(work['func'], work['name'])
                print 'Scheduled: {0}'.format(sched)
            else:
                print 'Function pointer {0} returned None value.'.format(sched)

    def parse_work_schedule(self, work):
        options = {
            'all': self.schedule.every().minute.do,
        }
        return options['all']


def main():
    t = TestSchedule()
    t.print_works()
    t.print_exec_works()
    t.run()

if __name__ == '__main__':
    main()
```

**Comment by dylwhich** [comment]
It looks like your problem is caused by reusing the schedule returned by `parse_work_schedule`, rather than where the functions are defined; you can see this by swapping the order in which you call `sched` -- only the last one called will actually be scheduled (this is expected, since `do` will just overwrite the job function each time it's called).

Instead, you could try something like changing `all` to a lambda so that it returns a new schedule every time:

    def parse_work_schedule(self, work):
        options = {
            'all': lambda: self.schedule.every().minute.do,
        }
        return options['all']

and then using it as such:

    for work in self.works:
        if sched and sched():
            sched()(pp, work['name'])
            sched()(work['func'], work['name'])
            print 'Scheduled: {0}'.format(sched)
        else:
            print 'Function pointer {0} returned None value.'.format(sched)

**Comment by denhua** [comment]
Hi dylwhich,

I tried your suggestion but it didn't work.

Perhaps I'm not clear with my question (and code).

If you uncomment and comment out:
sched(pp, work['name'])
# sched(work['func'], work['name'])

The code, as it is, works. However, when the comments are swapped, i.e.

# sched(pp, work['name'])
sched(work['func'], work['name'])

the code doesn't work. Why is that? Both are functions.

**Comment by denhua** [comment]
I found the answer. Both are not functions. pp is a function hence it works correctly. But work['func'] is an instancemethod type. So the solution is to have a method within the class that returns a function object. Then I can provide that function object to the schedule.

Thanks for your help.
