### ISSUE TITLE
Wrong documentation with timezone

### ISSUE THREAD

**Issue by nilansaha** [dbader/schedule#558]
```
schedule.every().day.at("12:42", "Europe/Amsterdam").do(job)
```

This piece of code just does not work. It shows that `at` excepts two arguments but three were given.

**Comment by jeremytanjianle** [comment]
The docs are correct. 
The issue is that the timezone feature is not yet in the stable released. 

to install the unstable but latest release with pip, do:
```
pip uninstall schedule
pip install git+https://github.com/dbader/schedule
```

I havent tested if timezone functions fully works as of yet.

**Comment by jeremytanjianle** [comment]
The docs are correct. 
The issue is that the timezone feature is not yet in the stable release. 

to install the unstable but latest release with pip, do:
```
pip uninstall schedule
pip install git+https://github.com/dbader/schedule
```

Though I havent tested if timezone functions fully works as of yet.

**Comment by SijmenHuizenga** [comment]
Just now 1.2.0 was released which adds the timezone argument in the `.at()`. Sorry for the delay!
