### ISSUE TITLE
Python 3.6 is not available in github actions `ubuntu-latest`

### ISSUE THREAD

**Issue by masa-08** [dbader/schedule#560]
I ran into this problem while trying to create a PR that would resolve another issue.
As mentioned in https://github.com/actions/setup-python/issues/561, ubuntu-latest is now ubuntu 22.04 and no longer supports python 3.6, so no PR will pass the test without changing the workflow.

Here is the error message for reference.

```shell
Run actions/setup-python@v2

Version 3.6 was not found in the local cache
Error: Version 3.6 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

**Comment by SijmenHuizenga** [comment]
Thank you for raising this issue. Has been resolved in #575. Now we can have green builds again :partying_face:
