### ISSUE TITLE
how to do a job everyday ,every 3 minute between 18:00 to 23:00 ?

### ISSUE THREAD

**Issue by ii0** [dbader/schedule#57]
In crontab it's:
*/5 18-23 * * * /home/me/job

Do you know how to realize it in schedule?
Many thanks!

**Comment by cfrco** [comment]
Hi wakeid,

There are no built-in solution now. One possible solution is you schedule a job every 3 mins. And then check the time before it start to run the real job.

**Comment by wakeid** [comment]
Thanks @cfrco ,I realize it like this, hope the code below helps : )
```python
def job(): 
    now = datetime.datetime.now()
    today6pm = now.replace(hour=18, minute=0, second=0, microsecond=0)
    today11pm = now.replace(hour=23, minute=0, second=0, microsecond=0)
    if not(today6pm<now<today11pm):return
    #do something here
```

**Comment by heisen273** [comment]
see https://github.com/dbader/schedule/issues/57
