### ISSUE TITLE
Documentation indicates no dependencies, but there is a dependency on pytz

### ISSUE THREAD

**Issue by rzuckerm** [dbader/schedule#586]
According to the documentation:
> Schedule has no dependencies. None. Zero. Nada. Nopes. We plan to keep it that way.

However, if you specify a timezone, there is a dependency on `pytz` [here](https://github.com/dbader/schedule/blob/master/schedule/__init__.py#L501).

**Comment by ArthurNRL** [comment]
https://schedule.readthedocs.io/en/stable/faq.html#modulenotfounderror-modulenotfounderror-no-module-named-pytz

**Comment by rzuckerm** [comment]
@ArthurNRL Yes, I saw that, but the documentation I quoted implies that there are no dependencies. That is misleading.

**Comment by Scratch-gu** [comment]
Welp you were using old docs so... That's what you get.

**Comment by rzuckerm** [comment]
[This](https://schedule.readthedocs.io/en/stable/installation.html#dependencies) is in the latest docs.

**Comment by Scratch-gu** [comment]
Does it really matter? And yes I just realized that those docs said it had no dependencies. That one paragraph needs to be fixed and that is all there is too it.

**Comment by SijmenHuizenga** [comment]
Fair point, docs have been updated in #601.
