### ISSUE TITLE
Potential problem of spawning sub processes

### ISSUE THREAD

**Issue by gssakash** [dbader/schedule#596]
Do I need to do anything special to handle the process not being terminated correctly incase I stop the execution of my program after which I expect it to stop the scheduler as well?
 
Do I need to be worried about the spawning of orphan processes on killing the main process which will keep running in the background which is not exactly what I want? And, how can I prevent this if it is a possibility that can occur while using this library?

**Comment by Agent-Hellboy** [comment]
Hi @gssakash, where are you using this, did you check the code? Is it creating a background process for job management? it's an in-process scheduler I guess, https://github.com/dbader/schedule/blob/master/schedule/__init__.py#L675

**Comment by gssakash** [comment]
Okay that makes sense, It was just a question I had and I have gotten a satisfactory answer.
This issue can now be closed.
