### ISSUE TITLE
Extend `schedule` to work as a decorator

### ISSUE THREAD

**Issue by tdhopper** [dbader/schedule#60]
I would love to see `schedule` extended to work as a decorator. I envision syntax along the lines of 

```
@schedule.every().hour.do
def job():
    print("I'm working...")
```

However, this doesn't work.

When thinking through this, I found that this does work now:

```
import schedule
import time

dec = schedule.every(2).seconds.do

@dec
def job():
    print("I'm working...")
```

Parentheses aren't allowed in decorators. (I think this is a result of [Guido's gut feeling](https://mail.python.org/pipermail/python-dev/2004-August/046711.html).) Syntax along the lines of this would be permitted: `@schedule.every.seconds.do`. 

Maybe it'd be insane, but we could implement something like `@schedule.every.ten.seconds.do`. There's probably a clever way to make that work for a large number of cases. Though, it doesn't resolve the issue of hard coding times.

Some discussion would be helpful before anyone tries implementing this.

**Comment by tdhopper** [comment]
Just spent some time trying figure out how to make the parentheses on `every` optional. I can't think of a sane way to do it though!

**Comment by rajathagasthya** [comment]
+1. Would love to have decorators, although I think it's tricky like @tdhopper mentioned.

**Comment by Contextualist** [comment]
@tdhopper love this idea, and I think it is feasible. with `__getattr__` method, it's possible to create something like `@schedule.every._10.seconds.do`.

**Comment by medecau** [comment]
This comes for free with CPython 3.9.

https://www.python.org/dev/peps/pep-0614/

**Comment by medecau** [comment]
Dear future visitor,

There is now a decorator for this. See #148.
