### ISSUE TITLE
Missing source distribution for 1.2.2

### ISSUE THREAD

**Issue by fryfrog** [dbader/schedule#627]
Hi,

I maintain the AUR [python-schedule](https://aur.archlinux.org/packages/python-schedule) package which depends on the source distribution. For some reason it is missing from 1.2.2, but is present in 1.2.1 (and presumably previous ones). Hopefully its an easy fix!

Thanks! :)

![Screenshot 2024-06-18 at 9 25 20 AM](https://github.com/dbader/schedule/assets/87748/6b96bf03-7812-445e-a6f1-14e0bfeca024)

![Screenshot 2024-06-18 at 9 25 31 AM](https://github.com/dbader/schedule/assets/87748/c70add5e-4ecf-4d0c-b25c-4cd4fc26ed1d)

**Comment by SijmenHuizenga** [comment]
Thanks for sharing, and thanks for maintaining the AUR distribution.

I changed the distribution from a [source distribution](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#source-distributions) to a [pure python wheel](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#pure-python-wheels). https://github.com/dbader/schedule/commit/82a43db1b938d8fdf60103bd41f329e06c8d3651#diff-9b171ca00cb885ccd9c997cb6f65fbb26d7eae92bf54bd7581b83c4541c156f2L62-R62 and didn't notice the lack of source package. I will see if i can fix that.

**Comment by SijmenHuizenga** [comment]
> even for a pure Python project, you should always upload both an sdist and a wheel to PyPI or other package indices [source](https://packaging.python.org/en/latest/discussions/package-formats/)

I learnt something :)

Source package has been uploaded

https://pypi.org/project/schedule/1.2.2

**Comment by fryfrog** [comment]
Worked a treat, thanks a bunch. :)
