### ISSUE TITLE
how to pass arguments when execute jobs in parallel？and Run a job in multiply duration? and etc

### ISSUE THREAD

**Issue by 631068264** [dbader/schedule#65]
Hi, I have some question to ask.

```
import threading
import time

import schedule


def job(name, j):
    print("I'm running on thread %s" % threading.current_thread() + name)
    print(6 + j)


def run_threaded(job_func, arg):
    threading.Thread(target=job_func, args=arg).start()


args = ("123", 6)

schedule.every(5).seconds.do(run_threaded, (job, args))
schedule.every(5).seconds.do(run_threaded, (job, args))

while 1:
    schedule.run_pending()
    time.sleep(1)
```
1. TypeError: run_threaded() takes exactly 2 arguments (1 given)
2.  How to run a job ? for example **10:00-13:00 , 15:00-16:00**
3.  How to know when the job finish and cancel it from schedule ?Or it will cancel itself ?

Schedule is a great tool .Thanks to its contributors.I hope it can has a better documentation.Because the example in README and FAQ is very simple.

**Comment by 631068264** [comment]
The first question has solved
`import threading
import time

import schedule


def job(name, j):
    print("I'm running on thread %s" % threading.current_thread() + name)
    print(6 + j)


def run_threaded(func, parm):
    threading.Thread(target=func, args=parm).start()


args = ("123", 6)
kw = {
    "func": job,
    "parm": args,
}
schedule.every(5).seconds.do(run_threaded, **kw)

while 1:
    schedule.run_pending()
    time.sleep(1)`

**Comment by anselal** [comment]
I think this answers your 2nd question https://schedule.readthedocs.io/en/stable/faq.html#how-to-run-a-job-at-random-intervals
