### ISSUE TITLE
Process stops running after first function call

### ISSUE THREAD

**Issue by chishaku** [dbader/schedule#66]
I added one of my functions to the basic starter example.  To start, the test function prints every 5 seconds as expected.  Then my function runs but when it completes, the whole process stops and the test function is no longer running every 5 seconds.  

Could there be something specific to my function that would cause the `while True` condition to break?

```
import schedule
import time
import datetime
import my_module

def test():
	print '{} This is a test'.format(datetime.datetime.now())

# Test run
schedule.every(5).seconds.do(test)
schedule.every().tuesday.at('14:16').do(my_module.function)

while True:
    schedule.run_pending()
    time.sleep(1)
```

**Comment by JIghtuse** [comment]
Well, your function definitely can terminate a program. See [this question](https://github.com/dbader/schedule/blob/master/FAQ.rst#what-if-my-task-throws-an-exception) in FAQ. If your function raises exception/call exit/have invalid syntax, it will terminate scheduler process.

    import schedule
    import time
    import datetime
    import sys


    def test():
        print('{} This is a test'.format(datetime.datetime.now()))


    def exit():
        sys.exit()

    schedule.every(5).seconds.do(test)
    schedule.every().saturday.at('11:47').do(exit)

    while True:
        schedule.run_pending()
        time.sleep(10)
