### ISSUE TITLE
Schedule Now

### ISSUE THREAD

**Issue by aashudwivedi** [dbader/schedule#67]
Currently adding a job like : 
```
    schedule.every(5).minutes.do(my_job)
```
will run the job after 5 min from now. add a func which lets the user to specify if the job should be run at the time of adding it. Example : 

```
    schedule.every(5).minutes.do(my_job).now(True)
```

**Comment by kosiraljaz** [comment]
Does schedule library support this?

**Comment by dbader** [comment]
Thanks for creating this issue! My thinking here is that we don't need to introduce a new schedule feature for that – we can just use a Python function call:

```python
schedule.every(5).minutes.do(my_job)
my_job()
```

Or alternatively, if we need to use this pattern several times we can write a simple helper function:

```python
def schedule_and_run_now(jobfunc):
    schedule.every(5).minutes.do(jobfunc)
    jobfunc()

schedule_and_run_now(my_job1)
schedule_and_run_now(my_job2)
schedule_and_run_now(my_job3)
```

**Comment by kosiraljaz** [comment]
actually I was looking through some examples and I saw `.run()` method.

`schedule.every(5).minutes.do(jobfunc).run()`

This seems to be working.
