### ISSUE TITLE
how to schedule task from user input?

### ISSUE THREAD

**Issue by sssseossss** [dbader/schedule#81]
Hi!
many thanks for useful library!
I have issue - i need to allow user to input scheduler according to his needs. Is there any way I could allow user to input scheduling command and input 'job' myself.
many thanks!

**Comment by dbader** [comment]
Hi @sssseossss 👋  There's nothing built into schedule directly that would help you do that, but you could certainly build your own input parsing on top of it. 

I don't think adding this functionality to schedule would help in the long run, as it's a separate concern IMO.

----
Thanks for your question. Closing this so we can keep the tracker clean of loose ends. Feel free to follow up (or make a separate issue) with more questions/discussion 😃
