### ISSUE TITLE
Job not running

### ISSUE THREAD

**Issue by kc-hyperaxes** [dbader/schedule#83]
There is one task out of several that is not running or getting scheduled for its next run incorrectly.
The task 'catalog_export' typically runs for 90-120 minutes so the start is occurs on one day at it finishes on the next day. We run it on the staging environment at 3am and it has never failed to run correctly, so I am wondering if the start date being different from the end date could be a factor. 

Before enabling schedule logging it failed twice. The pattern was that it ran successfully on the initial run, failed to run on the next night, ran sucessfully on the following (third) night, and then failed to run again on the fourth night.

The code says:
`schedule.every().day.at("23:25").do(catalog_export)
`
And it appears in the log:

> 2016-04-11 23:25:00,334 = schedule - INFO - Running job Every 1 day at 23:25:00 do catalog_export() (last run: [never], next run: 2016-04-11 23:25:00)

Here is one that worked without incident and was scheduled before catalog_export and ran the next day without incident.

> 2016-04-11 23:15:00,397 = schedule - INFO - Running job Every 1 day at 23:15:00 do customerAlias_load() (last run: [never], next run: 2016-04-11 23:15:00)
> 
> 2016-04-12 23:15:00,048 = schedule - INFO - Running job Every 1 day at 23:15:00 do customerAlias_load() (last run: 2016-04-11 23:16:55, next run: 2016-04-12 23:15:00)

But there is nothing in the log for catalog_export on 2016-04-12, 23:25 is just silent.

2016-04-12 23:16:51,927 = cat2es.customerAlias_load - INFO - finished at: 23:16:51 
2016-04-12 23:57:24,667 = schedule - INFO - Running job Every 60 minutes do heartbeat() (last run: 2016-04-12 22:57:24, next run: 2016-04-12 23:57:24)

There are two logs attached.
In the log for 20160411:
between lines 22-23: catalog_export fails to run
line 34: schedule log enabled
line 96: catalog_export starts, and is rescheduled

in the log for 20160412:
between lines 20-31: catalog_export fails to run

[cat2es_20160412_log.txt](https://github.com/dbader/schedule/files/219101/cat2es_20160412_log.txt)
[cat2es_20160411_log.txt](https://github.com/dbader/schedule/files/219102/cat2es_20160411_log.txt)

**Comment by kc-hyperaxes** [comment]
Is this a valid workaround?
```
schedule.every().monday.at("23:30").do(catalog_export())
schedule.every().tuesday.at("23:30").do(catalog_export())
schedule.every().wednesday.at("23:30").do(catalog_export())
schedule.every().thursday.at("23:30").do(catalog_export())
schedule.every().friday.at("23:30").do(catalog_export())
schedule.every().saturday.at("23:30").do(catalog_export())
schedule.every().sunday.at("23:30").do(catalog_export())
```

**Comment by kc-hyperaxes** [comment]
I tried using multiple threads as a workaround but it did not work either. I had to switch to APScheduler to fix this issue.

**Comment by dbader** [comment]
Hi @kc-hyperaxes 👋 

I'm linking this to the "logging improvements" ticket. That might help make it easier to diagnose what's going on in such situations in the future → #30 

Closing this for now so we can keep the tracker clean of loose ends. Feel free to follow up (or make a separate issue) with more questions/discussion 😃
