### ISSUE TITLE
how to run job only on weekends

### ISSUE THREAD

**Issue by grayaii** [dbader/schedule#85]
It would be great if it could do something like this:
schedule.every().sunday.every(4).hours.do(job)
schedule.every().saturday.every(4).hours.do(job)

Here is the cron syntax:
7 */4 \* \* 0,6

Maybe it can, I'm just not seeing how...

**Comment by grayaii** [comment]
I could break it up into multiple crons like so:

schedule.every().friday.at("0:0").do(job)
schedule.every().friday.at("4:0").do(job)
schedule.every().friday.at("8:0").do(job)
schedule.every().friday.at("12:0").do(job)
schedule.every().friday.at("16:0").do(job)
schedule.every().friday.at("20:0").do(job)
schedule.every().friday.at("24:0").do(job)

But if there is another way of doing this, that would great!

**Comment by skgbafa** [comment]
I'm seeking to do this as well, but for the weekdays! Just a note so that you know this is a desired feature.

**Comment by dbader** [comment]
Good point. I think if we wanted to add this we should cover both weekdays and weekends.

**Comment by dbader** [comment]
Let's move this discussion over to #99.
