### ISSUE TITLE
how can i run it when pc reboot

### ISSUE THREAD

**Issue by ghotiv** [dbader/schedule#86]

**Comment by xmikro** [comment]
If you are using a linux distro you can try creating a systemd service.

**Comment by alexmacniven** [comment]
Easiest way to do this on Windows is to put a shortcut to the py file you want to run in the Start folder

**Comment by dbader** [comment]
This is more of an operations question than something that directly relates to Schedule.

Thanks for your question. Closing this so we can keep the tracker clean of loose ends. Feel free to follow up (or make a separate issue) with more questions/discussion 😃
