### ISSUE TITLE
Can "at" method suport time format like ''15:00:03'' (i.e. accurate to seconds)?

### ISSUE THREAD

**Issue by yeyushi** [dbader/schedule#88]
At method is especially useful for doing time-specific operations. But I notice that it only support time format like "15:00" (i.e. accurate to minute), which is not very accurate in some circumstances (for example, quantitative trading)

**Comment by yeyushi** [comment]
state like "schedule.every().day.at("09:24:57").do(buy)" will give an error.

**Comment by dbader** [comment]
Hi @yeyushi 👋  I see how this could be useful and it could be added in a way that doesn't affect the current API. If someone has the bandwidth to add this then I think we should do it.

**Comment by dgrant** [comment]
My PR #116 does this.

**Comment by SijmenHuizenga** [comment]
This seems to be fixed:

```python
import schedule

def job():
    pass

schedule.every().day.at("09:24:57").do(job)
print(schedule.next_run())
```
It outputs `2021-01-05 09:24:57`, which seems correct.
