### ISSUE TITLE
Broken cashe

### ISSUE THREAD

**Issue by TDaltonC** [dbader/schedule#90]
The link to Adams blog post and the cashe of the blogpost are broken. Even if you don't intend to fix the link, could you send me a copy of the blog?

**Comment by dbader** [comment]
Hi @TDaltonC 👋  When I checked today the original link to Adam's blog post seemed to work again: http://adam.herokuapp.com/past/2010/4/13/rethinking_cron/

Closing this so we can keep the tracker clean of loose ends. Feel free to follow up (or make a separate issue) with more questions/discussion 😃
