### ISSUE TITLE
Run jobs in a different thread/process

### ISSUE THREAD

**Issue by Michael-F-Bryan** [dbader/schedule#92]
How hard would it be to refactor the scheduler to run jobs in a separate thread/process? 

For example, I was thinking you could use the `ThreadPoolExecutor` from the `concurrent.futures` module and then when you call `Scheduler._run_job()` instead of running the job inside that function, it will ask the `ThreadPoolExecutor` to run the job instead. That way you won't get the issue where one job will take a long time, meaning that the jobs meant to be run afterwards gets pushed back.

I imagine it wouldn't be too hard to implement this as a subclass of `Scheduler`.

**Comment by jpsutton** [comment]
Take a look at the FAQ ( https://github.com/dbader/schedule/blob/master/FAQ.rst ), which has a suggested work-around for running jobs via a thread wrapper function.  It works well enough for basic stuff.  The only issue I've had is that if you schedule a job to run every X minutes and it takes X+1 minutes to finish running, the scheduler has no idea it hasn't finished and just spawns another thread.

I've made a modification to my local copy of the library which handles this case well, but haven't sent a pull request just yet.

**Comment by SijmenHuizenga** [comment]
Hello there!

It isn't too difficult to refactor this library to run jobs in a separate thread...

However, it is pretty complex to implement that in a way that supports all the many requirements people have for multi-threading, and at the same time keep it super simple and prevents people from shooting themselves in the foot. Some other libraries, like `APSchedule`, do a great job solving these problems. This library isn't trying to compete with those libraries, instead it offers an alternative for the cases when only a very simple scheduling library is needed. I think it is best if we keep it simple and leave the more complex features (like multi threading) to the more complex scheduling libraries.

Of course, it is possible to add multi-threading on top of this library. Some examples are in the docs:

* Background execution: https://schedule.readthedocs.io/en/latest/background-execution.html
* Parallel execution: https://schedule.readthedocs.io/en/latest/parallel-execution.html
