### ISSUE TITLE
Install on android

### ISSUE THREAD

**Issue by dgreat91** [dbader/schedule#93]
Hi, 

Please is there a way to use this library on android set-top box?

**Comment by dbader** [comment]
Hi @dgreat91 if there's a way to run Python on that box it should be possible to run Schedule, too. Schedule is a pure-Python library with no 3rd party dependencies so your chances should be good 😃 

Thanks for your question. Closing this so we can keep the tracker clean of loose ends. Feel free to follow up (or make a separate issue) with more questions/discussion 😃
